//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericEdcStudySettings {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericEdcStudySettings object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericEdcStudySettings() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.Res" +
                                        "ources.GenericEdcStudySettings", typeof(GenericEdcStudySettings).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Apache Hop Base URL'.
        /// </summary>
        public static string ApacheHopBaseUrl {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopBaseUrl, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The base URL of Apache Hop Server '.
        /// </summary>
        public static string ApacheHopBaseUrlDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopBaseUrlDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Apache Hop Password'.
        /// </summary>
        public static string ApacheHopPassword {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopPassword, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The password used to authenticate requests on the Apache Hop Server'.
        /// </summary>
        public static string ApacheHopPasswordDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopPasswordDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Apache Hop Username'.
        /// </summary>
        public static string ApacheHopUsername {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopUsername, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The username used to authenticate requests on the Apache Hop Server'.
        /// </summary>
        public static string ApacheHopUsernameDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopUsernameDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '890 Data Transfer Generic Rave'.
        /// </summary>
        public static string DataTransferRaveCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferRaveCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '900 Data Transfer Generic Repeat Key'.
        /// </summary>
        public static string DataTransferRepeatKeyCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferRepeatKeyCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '895 Data Transfer Generic Veeva'.
        /// </summary>
        public static string DataTransferVeevaCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferVeevaCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enable Rave Error Notification'.
        /// </summary>
        public static string EnableRaveErrorNotification {
            get {
                return ResourceManager.GetString(ResourceNames.EnableRaveErrorNotification, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enable or disable RaveErrorNotification and the RaveErrorListNotification'.
        /// </summary>
        public static string EnableRaveErrorNotificationDescription {
            get {
                return ResourceManager.GetString(ResourceNames.EnableRaveErrorNotificationDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enable Veeva Error Notification'.
        /// </summary>
        public static string EnableVeevaErrorNotification {
            get {
                return ResourceManager.GetString(ResourceNames.EnableVeevaErrorNotification, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enable or disable VeevaErrorNotification and the VeevaErrorListNotification'.
        /// </summary>
        public static string EnableVeevaErrorNotificationDescription {
            get {
                return ResourceManager.GetString(ResourceNames.EnableVeevaErrorNotificationDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visits to be excluded from the Scheduled Visits list'.
        /// </summary>
        public static string ExcludeFromScheduledVisits {
            get {
                return ResourceManager.GetString(ResourceNames.ExcludeFromScheduledVisits, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Additional visits that will be excluded from the Scheduled Visits list (only &quot;visit.IsUnscheduled = false&quot; check is applied by default)'.
        /// </summary>
        public static string ExcludeFromScheduledVisitsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ExcludeFromScheduledVisitsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Informed Consent Visits'.
        /// </summary>
        public static string InformedConsentVisits {
            get {
                return ResourceManager.GetString(ResourceNames.InformedConsentVisits, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visits that should be processed as Informed Consent Visits'.
        /// </summary>
        public static string InformedConsentVisitsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.InformedConsentVisitsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Replacement Visits'.
        /// </summary>
        public static string ReplacementVisits {
            get {
                return ResourceManager.GetString(ResourceNames.ReplacementVisits, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visits that should be processed as Replacement Visits'.
        /// </summary>
        public static string ReplacementVisitsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ReplacementVisitsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Screen Fail Visits'.
        /// </summary>
        public static string ScreenFailVisits {
            get {
                return ResourceManager.GetString(ResourceNames.ScreenFailVisits, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visits that should be processed as Screen Fail Visits'.
        /// </summary>
        public static string ScreenFailVisitsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ScreenFailVisitsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unscheduled Visits'.
        /// </summary>
        public static string UnscheduledVisits {
            get {
                return ResourceManager.GetString(ResourceNames.UnscheduledVisits, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visits that should be processed as Unscheduled Visits'.
        /// </summary>
        public static string UnscheduledVisitsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.UnscheduledVisitsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ApacheHopBaseUrl'.
            /// </summary>
            public const string ApacheHopBaseUrl = "ApacheHopBaseUrl";
            
            /// <summary>
            /// Stores the resource name 'ApacheHopBaseUrlDescription'.
            /// </summary>
            public const string ApacheHopBaseUrlDescription = "ApacheHopBaseUrlDescription";
            
            /// <summary>
            /// Stores the resource name 'ApacheHopPassword'.
            /// </summary>
            public const string ApacheHopPassword = "ApacheHopPassword";
            
            /// <summary>
            /// Stores the resource name 'ApacheHopPasswordDescription'.
            /// </summary>
            public const string ApacheHopPasswordDescription = "ApacheHopPasswordDescription";
            
            /// <summary>
            /// Stores the resource name 'ApacheHopUsername'.
            /// </summary>
            public const string ApacheHopUsername = "ApacheHopUsername";
            
            /// <summary>
            /// Stores the resource name 'ApacheHopUsernameDescription'.
            /// </summary>
            public const string ApacheHopUsernameDescription = "ApacheHopUsernameDescription";
            
            /// <summary>
            /// Stores the resource name 'DataTransferRaveCategory'.
            /// </summary>
            public const string DataTransferRaveCategory = "DataTransferRaveCategory";
            
            /// <summary>
            /// Stores the resource name 'DataTransferRepeatKeyCategory'.
            /// </summary>
            public const string DataTransferRepeatKeyCategory = "DataTransferRepeatKeyCategory";
            
            /// <summary>
            /// Stores the resource name 'DataTransferVeevaCategory'.
            /// </summary>
            public const string DataTransferVeevaCategory = "DataTransferVeevaCategory";
            
            /// <summary>
            /// Stores the resource name 'EnableRaveErrorNotification'.
            /// </summary>
            public const string EnableRaveErrorNotification = "EnableRaveErrorNotification";
            
            /// <summary>
            /// Stores the resource name 'EnableRaveErrorNotificationDescription'.
            /// </summary>
            public const string EnableRaveErrorNotificationDescription = "EnableRaveErrorNotificationDescription";
            
            /// <summary>
            /// Stores the resource name 'EnableVeevaErrorNotification'.
            /// </summary>
            public const string EnableVeevaErrorNotification = "EnableVeevaErrorNotification";
            
            /// <summary>
            /// Stores the resource name 'EnableVeevaErrorNotificationDescription'.
            /// </summary>
            public const string EnableVeevaErrorNotificationDescription = "EnableVeevaErrorNotificationDescription";
            
            /// <summary>
            /// Stores the resource name 'ExcludeFromScheduledVisits'.
            /// </summary>
            public const string ExcludeFromScheduledVisits = "ExcludeFromScheduledVisits";
            
            /// <summary>
            /// Stores the resource name 'ExcludeFromScheduledVisitsDescription'.
            /// </summary>
            public const string ExcludeFromScheduledVisitsDescription = "ExcludeFromScheduledVisitsDescription";
            
            /// <summary>
            /// Stores the resource name 'InformedConsentVisits'.
            /// </summary>
            public const string InformedConsentVisits = "InformedConsentVisits";
            
            /// <summary>
            /// Stores the resource name 'InformedConsentVisitsDescription'.
            /// </summary>
            public const string InformedConsentVisitsDescription = "InformedConsentVisitsDescription";
            
            /// <summary>
            /// Stores the resource name 'ReplacementVisits'.
            /// </summary>
            public const string ReplacementVisits = "ReplacementVisits";
            
            /// <summary>
            /// Stores the resource name 'ReplacementVisitsDescription'.
            /// </summary>
            public const string ReplacementVisitsDescription = "ReplacementVisitsDescription";
            
            /// <summary>
            /// Stores the resource name 'ScreenFailVisits'.
            /// </summary>
            public const string ScreenFailVisits = "ScreenFailVisits";
            
            /// <summary>
            /// Stores the resource name 'ScreenFailVisitsDescription'.
            /// </summary>
            public const string ScreenFailVisitsDescription = "ScreenFailVisitsDescription";
            
            /// <summary>
            /// Stores the resource name 'UnscheduledVisits'.
            /// </summary>
            public const string UnscheduledVisits = "UnscheduledVisits";
            
            /// <summary>
            /// Stores the resource name 'UnscheduledVisitsDescription'.
            /// </summary>
            public const string UnscheduledVisitsDescription = "UnscheduledVisitsDescription";
        }
    }
}
