//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericEdcVisitSettings {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericEdcVisitSettings object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericEdcVisitSettings() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.Res" +
                                        "ources.GenericEdcVisitSettings", typeof(GenericEdcVisitSettings).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Generic Form Repeat Key'.
        /// </summary>
        public static string DataTransferFormRepeatKeyCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferFormRepeatKeyCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Generic ItemGroup Repeat Key'.
        /// </summary>
        public static string DataTransferItemGroupRepeatKeyCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferItemGroupRepeatKeyCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Generic StudyEvent Repeat Key'.
        /// </summary>
        public static string DataTransferStudyEventRepeatKeyCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferStudyEventRepeatKeyCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visit Name Mapping for EDC'.
        /// </summary>
        public static string EDCVisitNameMapping {
            get {
                return ResourceManager.GetString(ResourceNames.EDCVisitNameMapping, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Generic Visit Mapping'.
        /// </summary>
        public static string EDCVisitNameMappingCategory {
            get {
                return ResourceManager.GetString(ResourceNames.EDCVisitNameMappingCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Value for mapping IRT Visit Names before EDC'.
        /// </summary>
        public static string EDCVisitNameMappingDescription {
            get {
                return ResourceManager.GetString(ResourceNames.EDCVisitNameMappingDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First Generic ItemGroup Repeat Key Format'.
        /// </summary>
        public static string FirstItemGroupRepeatKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.FirstItemGroupRepeatKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Will be applied to the first ItemGroup Repeat Key in the folder (they are different in some studies). Can be empty, which means there is no different First ItemGroup Repeat Key format (ex. &quot;RK{0}&quot;, default is “{0}”). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        public static string FirstItemGroupRepeatKeyFormatDescription {
            get {
                return ResourceManager.GetString(ResourceNames.FirstItemGroupRepeatKeyFormatDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First Generic StudyEvent Repeat Key Format'.
        /// </summary>
        public static string FirstStudyEventRepeatKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.FirstStudyEventRepeatKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Will be applied to the first StudyEvent Repeat Key in the folder (they are different in some studies). Can be empty, which means there is no different First StudyEvent Repeat Key format. {0} - RepeatKey, {1} - Scheduled RepeatKey, {2} - Unscheduled RepeatKey, {3} – ReplacementRepeatKey, {4} – ScreenFailRepeatKey, {5} – InformedConsentRepeatKey (ex. &quot;P{0}[1]/DAYN6N1P{0}[1]&quot;). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        public static string FirstStudyEventRepeatKeyFormatDescription {
            get {
                return ResourceManager.GetString(ResourceNames.FirstStudyEventRepeatKeyFormatDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic Form Repeat Key Format'.
        /// </summary>
        public static string FormRepeatKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.FormRepeatKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Free text constant string (Form Repeat Key should be enabled in the Notification Definition settings). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        public static string FormRepeatKeyFormatDescription {
            get {
                return ResourceManager.GetString(ResourceNames.FormRepeatKeyFormatDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic ItemGroup Repeat Key Format'.
        /// </summary>
        public static string ItemGroupRepeatKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.ItemGroupRepeatKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic ItemGroup Repeat Key Format (ex. &quot;RK{0}&quot;, default is “{0}”). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        public static string ItemGroupRepeatKeyFormatDescription {
            get {
                return ResourceManager.GetString(ResourceNames.ItemGroupRepeatKeyFormatDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic StudyEvent Repeat Key Format'.
        /// </summary>
        public static string StudyEventRepeatKeyFormat {
            get {
                return ResourceManager.GetString(ResourceNames.StudyEventRepeatKeyFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} - RepeatKey, {1} - Scheduled RepeatKey, {2} - Unscheduled RepeatKey, {3} – ReplacementRepeatKey, {4} – ScreenFailRepeatKey, {5} – InformedConsentRepeatKey (ex. &quot;P{0}[1]/DAYN6N1[1]&quot;). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        public static string StudyEventRepeatKeyFormatDescription {
            get {
                return ResourceManager.GetString(ResourceNames.StudyEventRepeatKeyFormatDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Will be applied to the first ItemGroup Repeat Key in the folder (they are different in some studies). Can be empty, which means there is no different First ItemGroup Repeat Key format (ex. &quot;RK{0}&quot;, default is “{0}”). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string FirstItemGroupRepeatKeyFormatDescriptionFormat(object arg0) {
            return string.Format(_resourceCulture, FirstItemGroupRepeatKeyFormatDescription, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Will be applied to the first StudyEvent Repeat Key in the folder (they are different in some studies). Can be empty, which means there is no different First StudyEvent Repeat Key format. {0} - RepeatKey, {1} - Scheduled RepeatKey, {2} - Unscheduled RepeatKey, {3} – ReplacementRepeatKey, {4} – ScreenFailRepeatKey, {5} – InformedConsentRepeatKey (ex. &quot;P{0}[1]/DAYN6N1P{0}[1]&quot;). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <param name="arg3">An object (3) to format.</param>
        /// <param name="arg4">An object (4) to format.</param>
        /// <param name="arg5">An object (5) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1025:ReplaceRepetitiveArgumentsWithParamsArray")]
        public static string FirstStudyEventRepeatKeyFormatDescriptionFormat(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) {
            return string.Format(_resourceCulture, FirstStudyEventRepeatKeyFormatDescription, arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Generic ItemGroup Repeat Key Format (ex. &quot;RK{0}&quot;, default is “{0}”). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ItemGroupRepeatKeyFormatDescriptionFormat(object arg0) {
            return string.Format(_resourceCulture, ItemGroupRepeatKeyFormatDescription, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} - RepeatKey, {1} - Scheduled RepeatKey, {2} - Unscheduled RepeatKey, {3} – ReplacementRepeatKey, {4} – ScreenFailRepeatKey, {5} – InformedConsentRepeatKey (ex. &quot;P{0}[1]/DAYN6N1[1]&quot;). Note: overwrites the same Notification Definition setting'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <param name="arg3">An object (3) to format.</param>
        /// <param name="arg4">An object (4) to format.</param>
        /// <param name="arg5">An object (5) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1025:ReplaceRepetitiveArgumentsWithParamsArray")]
        public static string StudyEventRepeatKeyFormatDescriptionFormat(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) {
            return string.Format(_resourceCulture, StudyEventRepeatKeyFormatDescription, arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'DataTransferFormRepeatKeyCategory'.
            /// </summary>
            public const string DataTransferFormRepeatKeyCategory = "DataTransferFormRepeatKeyCategory";
            
            /// <summary>
            /// Stores the resource name 'DataTransferItemGroupRepeatKeyCategory'.
            /// </summary>
            public const string DataTransferItemGroupRepeatKeyCategory = "DataTransferItemGroupRepeatKeyCategory";
            
            /// <summary>
            /// Stores the resource name 'DataTransferStudyEventRepeatKeyCategory'.
            /// </summary>
            public const string DataTransferStudyEventRepeatKeyCategory = "DataTransferStudyEventRepeatKeyCategory";
            
            /// <summary>
            /// Stores the resource name 'EDCVisitNameMapping'.
            /// </summary>
            public const string EDCVisitNameMapping = "EDCVisitNameMapping";
            
            /// <summary>
            /// Stores the resource name 'EDCVisitNameMappingCategory'.
            /// </summary>
            public const string EDCVisitNameMappingCategory = "EDCVisitNameMappingCategory";
            
            /// <summary>
            /// Stores the resource name 'EDCVisitNameMappingDescription'.
            /// </summary>
            public const string EDCVisitNameMappingDescription = "EDCVisitNameMappingDescription";
            
            /// <summary>
            /// Stores the resource name 'FirstItemGroupRepeatKeyFormat'.
            /// </summary>
            public const string FirstItemGroupRepeatKeyFormat = "FirstItemGroupRepeatKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'FirstItemGroupRepeatKeyFormatDescription'.
            /// </summary>
            public const string FirstItemGroupRepeatKeyFormatDescription = "FirstItemGroupRepeatKeyFormatDescription";
            
            /// <summary>
            /// Stores the resource name 'FirstStudyEventRepeatKeyFormat'.
            /// </summary>
            public const string FirstStudyEventRepeatKeyFormat = "FirstStudyEventRepeatKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'FirstStudyEventRepeatKeyFormatDescription'.
            /// </summary>
            public const string FirstStudyEventRepeatKeyFormatDescription = "FirstStudyEventRepeatKeyFormatDescription";
            
            /// <summary>
            /// Stores the resource name 'FormRepeatKeyFormat'.
            /// </summary>
            public const string FormRepeatKeyFormat = "FormRepeatKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'FormRepeatKeyFormatDescription'.
            /// </summary>
            public const string FormRepeatKeyFormatDescription = "FormRepeatKeyFormatDescription";
            
            /// <summary>
            /// Stores the resource name 'ItemGroupRepeatKeyFormat'.
            /// </summary>
            public const string ItemGroupRepeatKeyFormat = "ItemGroupRepeatKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'ItemGroupRepeatKeyFormatDescription'.
            /// </summary>
            public const string ItemGroupRepeatKeyFormatDescription = "ItemGroupRepeatKeyFormatDescription";
            
            /// <summary>
            /// Stores the resource name 'StudyEventRepeatKeyFormat'.
            /// </summary>
            public const string StudyEventRepeatKeyFormat = "StudyEventRepeatKeyFormat";
            
            /// <summary>
            /// Stores the resource name 'StudyEventRepeatKeyFormatDescription'.
            /// </summary>
            public const string StudyEventRepeatKeyFormatDescription = "StudyEventRepeatKeyFormatDescription";
        }
    }
}
