// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Globalization;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Queries.Controllers
{
    /// <summary>
    /// The generated side of ReceivedNotificationQueriesController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Queries")]
    // old routes -- [Route("api/IRT/v1/DTGeneric/Queries/ReceivedNotification")]
    [Produces("application/json")]
    public partial class ReceivedNotificationQueriesController : QueriesController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public ReceivedNotificationQueriesController
        (
            IRT.Modules.DataTransfer.Generic.Domain.Notifications.DataServices.ReceivedNotificationDataService dataService,
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
            ReceivedNotificationDataService = dataService;
        }
        
        /// <summary>
        /// CountryName handler endpoint
        /// </summary>
        /// <param name="countryCode">countryCode</param>
        [HttpGet]
        // old routes -- [Route("CountryName")]
         [Route("api/irt/v1/data-transfer-generic/queries/received-notification/country-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetCountryName
        (
             string countryCode
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = ReceivedNotificationDataService.GetCountryName
                (
                     countryCode
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// DepotCountryName handler endpoint
        /// </summary>
        /// <param name="depotId">depotId</param>
        [HttpGet]
        // old routes -- [Route("DepotCountryName")]
         [Route("api/irt/v1/data-transfer-generic/queries/received-notification/depot-country-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetDepotCountryName
        (
             string depotId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = ReceivedNotificationDataService.GetDepotCountryName
                (
                     depotId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// DepotName handler endpoint
        /// </summary>
        /// <param name="depotId">depotId</param>
        [HttpGet]
        // old routes -- [Route("DepotName")]
         [Route("api/irt/v1/data-transfer-generic/queries/received-notification/depot-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetDepotName
        (
             string depotId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = ReceivedNotificationDataService.GetDepotName
                (
                     depotId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }

        protected IRT.Modules.DataTransfer.Generic.Domain.Notifications.DataServices.ReceivedNotificationDataService ReceivedNotificationDataService;    
    }
}
