//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Edc.Domain.Jobs.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class FailedSendingJobResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a FailedSendingJobResources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public FailedSendingJobResources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Edc.Domain.Jobs.Resources.FailedSendingJo" +
                                        "bResources", typeof(FailedSendingJobResources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Sending Is Not Enabled'.
        /// </summary>
        public static string LocalizedMessage_DataTransferSendingIsNotEnabled {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_DataTransferSendingIsNotEnabled, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Failed Data Transfer Sending Is Not Enabled'.
        /// </summary>
        public static string LocalizedMessage_FailedDataTransferSendingIsNotEnabled {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_FailedDataTransferSendingIsNotEnabled, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Finished sending Notifications for {0}'.
        /// </summary>
        public static string LocalizedMessage_FinishedSendingNotifications {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_FinishedSendingNotifications, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'No NotificationDefinition found for {0}'.
        /// </summary>
        public static string LocalizedMessage_NoNotificationDefinitionFoundFor {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_NoNotificationDefinitionFoundFor, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Found {0} {1} notifications to send.'.
        /// </summary>
        public static string LocalizedMessage_SendingCount {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_SendingCount, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Started sending Notifications for {0}'.
        /// </summary>
        public static string LocalizedMessage_StartedSendingNotifications {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_StartedSendingNotifications, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} failed notifications summary completed'.
        /// </summary>
        public static string LocalizedMessage_SummaryCompleted {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_SummaryCompleted, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Found {0} {1} notifications to send'.
        /// </summary>
        public static string LocalizedMessage_SummaryCount {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_SummaryCount, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} failed notifications summary started'.
        /// </summary>
        public static string LocalizedMessage_SummaryStarted {
            get {
                return ResourceManager.GetString(ResourceNames.LocalizedMessage_SummaryStarted, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Finished sending Notifications for {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_FinishedSendingNotificationsFormat(object arg0) {
            return string.Format(_resourceCulture, LocalizedMessage_FinishedSendingNotifications, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'No NotificationDefinition found for {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_NoNotificationDefinitionFoundForFormat(object arg0) {
            return string.Format(_resourceCulture, LocalizedMessage_NoNotificationDefinitionFoundFor, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Found {0} {1} notifications to send.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_SendingCountFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, LocalizedMessage_SendingCount, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Started sending Notifications for {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_StartedSendingNotificationsFormat(object arg0) {
            return string.Format(_resourceCulture, LocalizedMessage_StartedSendingNotifications, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} failed notifications summary completed'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_SummaryCompletedFormat(object arg0) {
            return string.Format(_resourceCulture, LocalizedMessage_SummaryCompleted, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Found {0} {1} notifications to send'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_SummaryCountFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, LocalizedMessage_SummaryCount, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} failed notifications summary started'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LocalizedMessage_SummaryStartedFormat(object arg0) {
            return string.Format(_resourceCulture, LocalizedMessage_SummaryStarted, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_DataTransferSendingIsNotEnabled'.
            /// </summary>
            public const string LocalizedMessage_DataTransferSendingIsNotEnabled = "LocalizedMessage_DataTransferSendingIsNotEnabled";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_FailedDataTransferSendingIsNotEnabled'.
            /// </summary>
            public const string LocalizedMessage_FailedDataTransferSendingIsNotEnabled = "LocalizedMessage_FailedDataTransferSendingIsNotEnabled";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_FinishedSendingNotifications'.
            /// </summary>
            public const string LocalizedMessage_FinishedSendingNotifications = "LocalizedMessage_FinishedSendingNotifications";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_NoNotificationDefinitionFoundFor'.
            /// </summary>
            public const string LocalizedMessage_NoNotificationDefinitionFoundFor = "LocalizedMessage_NoNotificationDefinitionFoundFor";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_SendingCount'.
            /// </summary>
            public const string LocalizedMessage_SendingCount = "LocalizedMessage_SendingCount";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_StartedSendingNotifications'.
            /// </summary>
            public const string LocalizedMessage_StartedSendingNotifications = "LocalizedMessage_StartedSendingNotifications";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_SummaryCompleted'.
            /// </summary>
            public const string LocalizedMessage_SummaryCompleted = "LocalizedMessage_SummaryCompleted";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_SummaryCount'.
            /// </summary>
            public const string LocalizedMessage_SummaryCount = "LocalizedMessage_SummaryCount";
            
            /// <summary>
            /// Stores the resource name 'LocalizedMessage_SummaryStarted'.
            /// </summary>
            public const string LocalizedMessage_SummaryStarted = "LocalizedMessage_SummaryStarted";
        }
    }
}
