//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ManageDynamicSettings.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Create {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Create object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Create() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ManageDyn" +
                                        "amicSettings.Resources.Create", typeof(Create).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cancel'.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString(ResourceNames.Cancel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Close'.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString(ResourceNames.Close, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Create Dynamic Setting'.
        /// </summary>
        public static string CreateDynamicSettingTitle {
            get {
                return ResourceManager.GetString(ResourceNames.CreateDynamicSettingTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&lt; {0} &gt;'.
        /// </summary>
        public static string DropdownPlaceholderFormat {
            get {
                return ResourceManager.GetString(ResourceNames.DropdownPlaceholderFormat, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Select'.
        /// </summary>
        public static string DropdownPlaceholderText {
            get {
                return ResourceManager.GetString(ResourceNames.DropdownPlaceholderText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Setting was successfully created.'.
        /// </summary>
        public static string DynamicSettingWasSuccessfullyCreated {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicSettingWasSuccessfullyCreated, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Save'.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString(ResourceNames.Save, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to '&lt; {0} &gt;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string DropdownPlaceholderFormatFormat(object arg0) {
            return string.Format(_resourceCulture, DropdownPlaceholderFormat, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Cancel'.
            /// </summary>
            public const string Cancel = "Cancel";
            
            /// <summary>
            /// Stores the resource name 'Close'.
            /// </summary>
            public const string Close = "Close";
            
            /// <summary>
            /// Stores the resource name 'CreateDynamicSettingTitle'.
            /// </summary>
            public const string CreateDynamicSettingTitle = "CreateDynamicSettingTitle";
            
            /// <summary>
            /// Stores the resource name 'DropdownPlaceholderFormat'.
            /// </summary>
            public const string DropdownPlaceholderFormat = "DropdownPlaceholderFormat";
            
            /// <summary>
            /// Stores the resource name 'DropdownPlaceholderText'.
            /// </summary>
            public const string DropdownPlaceholderText = "DropdownPlaceholderText";
            
            /// <summary>
            /// Stores the resource name 'DynamicSettingWasSuccessfullyCreated'.
            /// </summary>
            public const string DynamicSettingWasSuccessfullyCreated = "DynamicSettingWasSuccessfullyCreated";
            
            /// <summary>
            /// Stores the resource name 'Save'.
            /// </summary>
            public const string Save = "Save";
        }
    }
}
