// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource))]
    public class DynamicResourceNullTypeDto
    {
        public System.String ResourceId { get; set; }
        public System.String Name { get; set; }
        public System.String Value { get; set; }
        public System.String Comment { get; set; }
        public System.String NameReadOnly { get; set; }
    }

    public class DynamicResourceNullTypeDtoInput
    {
        public System.String Name { get; set; }
        public System.String Value { get; set; }
        public System.String Comment { get; set; }
        public System.String NameReadOnly { get; set; }
    }
}