// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.GenericDataTransferStudySettings))]
    public class GenericDataTransferStudySettingsNullTypeDto
    {
        public System.String StudyId { get; set; }
        public System.String UseGenericDataTransfer { get; set; }
        public System.String Timeout { get; set; }
        public System.String MaxNumberOfRetriesForClientNotifications { get; set; }
        public System.String MaxNumberOfRetriesForApacheHealthCheck { get; set; }
    }

    public class GenericDataTransferStudySettingsNullTypeDtoInput
    {
        public System.String UseGenericDataTransfer { get; set; }
        public System.String Timeout { get; set; }
        public System.String MaxNumberOfRetriesForClientNotifications { get; set; }
        public System.String MaxNumberOfRetriesForApacheHealthCheck { get; set; }
    }
}