// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings))]
    public class NotificationGenerationSettingsNullTypeDto
    {
        public System.String EntityId { get; set; }
        public System.String Name { get; set; }
        public System.String NotificationDefinition { get; set; }
        public System.String GenerationOrder { get; set; }
        public System.String ShouldGenerateFormProviderId { get; set; }
        public System.String VisitId { get; set; }
        public System.String SubjectVisitCapturedDataPoints { get; set; }
        public System.String ValueToCompare { get; set; }
        public System.String SelfSupportActions { get; set; }
    }

    public class NotificationGenerationSettingsNullTypeDtoInput
    {
        public System.String Name { get; set; }
        public System.String NotificationDefinition { get; set; }
        public System.String GenerationOrder { get; set; }
        public System.String ShouldGenerateFormProviderId { get; set; }
        public System.String VisitId { get; set; }
        public System.String SubjectVisitCapturedDataPoints { get; set; }
        public System.String ValueToCompare { get; set; }
        public System.String SelfSupportActions { get; set; }
    }
}