// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using IRT.Domain;
using Kernel.SharedDomain.Security;

namespace Api.Irt.Shared.Security
{
	public static class RightsManifest
	{
		public static string[,] Declaration =
		{
		};
	}
}
