// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

namespace Api.Irt.Modules.DataTransfer.Generic.Events
{
	public class EventClassification : IrtApiCreator.ModuleSpecifics.Contracts.EventClassification.EventClassification, 
	IrtApiCreator.ModuleSpecifics.Contracts.EventClassification.IEventClassification
	{
		public EventClassification()
		{
			Declaration = new string[,]
			{

                {"IRT.Modules.DataTransfer.Generic.Edc.Domain.Aggregates.ClientNotifications.Events.DataTransferErrorNotificationCreated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Edc.Domain.Aggregates.ClientNotifications.Events.Veeva.VeevaDataTransferErrorSummaryNotificationCreated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Edc.Domain.Aggregates.ClientNotifications.Events.Rave.RaveDataTransferErrorSummaryNotificationCreated", "DTGeneric"}

			};
		}
	}
}