//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericStudySettings {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericStudySettings object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericStudySettings() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.Resourc" +
                                        "es.GenericStudySettings", typeof(GenericStudySettings).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '880 Data Transfer Generic'.
        /// </summary>
        public static string DataTransferCategory {
            get {
                return ResourceManager.GetString(ResourceNames.DataTransferCategory, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Max Number of Retries for Apache Health Check'.
        /// </summary>
        public static string MaxNumberOfRetriesApacheHealthCheck {
            get {
                return ResourceManager.GetString(ResourceNames.MaxNumberOfRetriesApacheHealthCheck, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The maximum number of attempts for sending Health Check http requests to Apache Hop Server endpoints. (default: 3) '.
        /// </summary>
        public static string MaxNumberOfRetriesApacheHealthCheckDescription {
            get {
                return ResourceManager.GetString(ResourceNames.MaxNumberOfRetriesApacheHealthCheckDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Max Number of Retries for Client Notifications'.
        /// </summary>
        public static string MaxNumberOfRetriesClientNotifications {
            get {
                return ResourceManager.GetString(ResourceNames.MaxNumberOfRetriesClientNotifications, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The maximum number of attempts for sending Client Notifications to Apache Hop Server. Using a value less than 0 will set the maximum number of attempts to infinite.'.
        /// </summary>
        public static string MaxNumberOfRetriesClientNotificationsDescription {
            get {
                return ResourceManager.GetString(ResourceNames.MaxNumberOfRetriesClientNotificationsDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Timeout'.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString(ResourceNames.Timeout, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The duration in seconds to wait before a request to Apache Hop Server times out'.
        /// </summary>
        public static string TimeoutDescription {
            get {
                return ResourceManager.GetString(ResourceNames.TimeoutDescription, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Use Generic Data Transfer'.
        /// </summary>
        public static string UseGenericDataTransfer {
            get {
                return ResourceManager.GetString(ResourceNames.UseGenericDataTransfer, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'DataTransferCategory'.
            /// </summary>
            public const string DataTransferCategory = "DataTransferCategory";
            
            /// <summary>
            /// Stores the resource name 'MaxNumberOfRetriesApacheHealthCheck'.
            /// </summary>
            public const string MaxNumberOfRetriesApacheHealthCheck = "MaxNumberOfRetriesApacheHealthCheck";
            
            /// <summary>
            /// Stores the resource name 'MaxNumberOfRetriesApacheHealthCheckDescription'.
            /// </summary>
            public const string MaxNumberOfRetriesApacheHealthCheckDescription = "MaxNumberOfRetriesApacheHealthCheckDescription";
            
            /// <summary>
            /// Stores the resource name 'MaxNumberOfRetriesClientNotifications'.
            /// </summary>
            public const string MaxNumberOfRetriesClientNotifications = "MaxNumberOfRetriesClientNotifications";
            
            /// <summary>
            /// Stores the resource name 'MaxNumberOfRetriesClientNotificationsDescription'.
            /// </summary>
            public const string MaxNumberOfRetriesClientNotificationsDescription = "MaxNumberOfRetriesClientNotificationsDescription";
            
            /// <summary>
            /// Stores the resource name 'Timeout'.
            /// </summary>
            public const string Timeout = "Timeout";
            
            /// <summary>
            /// Stores the resource name 'TimeoutDescription'.
            /// </summary>
            public const string TimeoutDescription = "TimeoutDescription";
            
            /// <summary>
            /// Stores the resource name 'UseGenericDataTransfer'.
            /// </summary>
            public const string UseGenericDataTransfer = "UseGenericDataTransfer";
        }
    }
}
