//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class NotificationGenerationSettings {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a NotificationGenerationSettings object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public NotificationGenerationSettings() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.Resourc" +
                                        "es.NotificationGenerationSettings", typeof(NotificationGenerationSettings).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Forms are generated based on this order, from the lowest value to the highest value. Multiple forms can have the same generation order (generation order is not guaranteed in this case).'.
        /// </summary>
        public static string GenerationOrder_Description {
            get {
                return ResourceManager.GetString(ResourceNames.GenerationOrder_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generation Order'.
        /// </summary>
        public static string GenerationOrder_Name {
            get {
                return ResourceManager.GetString(ResourceNames.GenerationOrder_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Message Envelope'.
        /// </summary>
        public static string MessageEnvelopeEntityId_Name {
            get {
                return ResourceManager.GetString(ResourceNames.MessageEnvelopeEntityId_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name'.
        /// </summary>
        public static string Name_Name {
            get {
                return ResourceManager.GetString(ResourceNames.Name_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Notification Definition template to use for generation'.
        /// </summary>
        public static string NotificationDefinition_Description {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationDefinition_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Notification Definition'.
        /// </summary>
        public static string NotificationDefinition_Name {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationDefinition_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Self Support Action(s) that should generate a form'.
        /// </summary>
        public static string SelfSupportAction_Description {
            get {
                return ResourceManager.GetString(ResourceNames.SelfSupportAction_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Self Support Action(s)'.
        /// </summary>
        public static string SelfSupportAction_Name {
            get {
                return ResourceManager.GetString(ResourceNames.SelfSupportAction_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Should Generate Form provider is used to determine if a form must be generated or not.'.
        /// </summary>
        public static string ShouldGenerateFormProviderId_Description {
            get {
                return ResourceManager.GetString(ResourceNames.ShouldGenerateFormProviderId_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Should Generate Form Provider'.
        /// </summary>
        public static string ShouldGenerateFormProviderId_Name {
            get {
                return ResourceManager.GetString(ResourceNames.ShouldGenerateFormProviderId_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Site'.
        /// </summary>
        public static string SiteEntityId_Name {
            get {
                return ResourceManager.GetString(ResourceNames.SiteEntityId_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject'.
        /// </summary>
        public static string SubjectEntityId {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectEntityId, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject Visit Captured Data used to identify when a form should generate or not'.
        /// </summary>
        public static string SubjectVisitCapturedData_Description {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectVisitCapturedData_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject Visit Captured Data Item'.
        /// </summary>
        public static string SubjectVisitCapturedData_Name {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectVisitCapturedData_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Trigger'.
        /// </summary>
        public static string TriggerEntityId_Name {
            get {
                return ResourceManager.GetString(ResourceNames.TriggerEntityId_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'If needed to compare a captured data point with a value, specify it here'.
        /// </summary>
        public static string ValueComparison_Description {
            get {
                return ResourceManager.GetString(ResourceNames.ValueComparison_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Value for comparison'.
        /// </summary>
        public static string ValueComparison_Name {
            get {
                return ResourceManager.GetString(ResourceNames.ValueComparison_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visit'.
        /// </summary>
        public static string VisitEntityId {
            get {
                return ResourceManager.GetString(ResourceNames.VisitEntityId, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visit Id(s) associated with trigger'.
        /// </summary>
        public static string VisitId_Description {
            get {
                return ResourceManager.GetString(ResourceNames.VisitId_Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Visit Id for Trigger'.
        /// </summary>
        public static string VisitId_Name {
            get {
                return ResourceManager.GetString(ResourceNames.VisitId_Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'GenerationOrder_Description'.
            /// </summary>
            public const string GenerationOrder_Description = "GenerationOrder_Description";
            
            /// <summary>
            /// Stores the resource name 'GenerationOrder_Name'.
            /// </summary>
            public const string GenerationOrder_Name = "GenerationOrder_Name";
            
            /// <summary>
            /// Stores the resource name 'MessageEnvelopeEntityId_Name'.
            /// </summary>
            public const string MessageEnvelopeEntityId_Name = "MessageEnvelopeEntityId_Name";
            
            /// <summary>
            /// Stores the resource name 'Name_Name'.
            /// </summary>
            public const string Name_Name = "Name_Name";
            
            /// <summary>
            /// Stores the resource name 'NotificationDefinition_Description'.
            /// </summary>
            public const string NotificationDefinition_Description = "NotificationDefinition_Description";
            
            /// <summary>
            /// Stores the resource name 'NotificationDefinition_Name'.
            /// </summary>
            public const string NotificationDefinition_Name = "NotificationDefinition_Name";
            
            /// <summary>
            /// Stores the resource name 'SelfSupportAction_Description'.
            /// </summary>
            public const string SelfSupportAction_Description = "SelfSupportAction_Description";
            
            /// <summary>
            /// Stores the resource name 'SelfSupportAction_Name'.
            /// </summary>
            public const string SelfSupportAction_Name = "SelfSupportAction_Name";
            
            /// <summary>
            /// Stores the resource name 'ShouldGenerateFormProviderId_Description'.
            /// </summary>
            public const string ShouldGenerateFormProviderId_Description = "ShouldGenerateFormProviderId_Description";
            
            /// <summary>
            /// Stores the resource name 'ShouldGenerateFormProviderId_Name'.
            /// </summary>
            public const string ShouldGenerateFormProviderId_Name = "ShouldGenerateFormProviderId_Name";
            
            /// <summary>
            /// Stores the resource name 'SiteEntityId_Name'.
            /// </summary>
            public const string SiteEntityId_Name = "SiteEntityId_Name";
            
            /// <summary>
            /// Stores the resource name 'SubjectEntityId'.
            /// </summary>
            public const string SubjectEntityId = "SubjectEntityId";
            
            /// <summary>
            /// Stores the resource name 'SubjectVisitCapturedData_Description'.
            /// </summary>
            public const string SubjectVisitCapturedData_Description = "SubjectVisitCapturedData_Description";
            
            /// <summary>
            /// Stores the resource name 'SubjectVisitCapturedData_Name'.
            /// </summary>
            public const string SubjectVisitCapturedData_Name = "SubjectVisitCapturedData_Name";
            
            /// <summary>
            /// Stores the resource name 'TriggerEntityId_Name'.
            /// </summary>
            public const string TriggerEntityId_Name = "TriggerEntityId_Name";
            
            /// <summary>
            /// Stores the resource name 'ValueComparison_Description'.
            /// </summary>
            public const string ValueComparison_Description = "ValueComparison_Description";
            
            /// <summary>
            /// Stores the resource name 'ValueComparison_Name'.
            /// </summary>
            public const string ValueComparison_Name = "ValueComparison_Name";
            
            /// <summary>
            /// Stores the resource name 'VisitEntityId'.
            /// </summary>
            public const string VisitEntityId = "VisitEntityId";
            
            /// <summary>
            /// Stores the resource name 'VisitId_Description'.
            /// </summary>
            public const string VisitId_Description = "VisitId_Description";
            
            /// <summary>
            /// Stores the resource name 'VisitId_Name'.
            /// </summary>
            public const string VisitId_Name = "VisitId_Name";
        }
    }
}
