//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class DynamicExtendedPropertiesResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a DynamicExtendedPropertiesResources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DynamicExtendedPropertiesResources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.Resources.DynamicExtendedPropertie" +
                                        "sResources", typeof(DynamicExtendedPropertiesResources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Our records indicate Name &apos;{1}&apos; already exists.'.
        /// </summary>
        public static string DynamicResourceDuplicateName {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceDuplicateName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Our records indicate a Name with Value &apos;{1}&apos; already exists.'.
        /// </summary>
        public static string DynamicResourceDuplicateValue {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceDuplicateValue, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Resource'.
        /// </summary>
        public static string DynamicResourceEntityTypeDisplayName {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceEntityTypeDisplayName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'DynamicResources'.
        /// </summary>
        public static string DynamicResourceExportFileName {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceExportFileName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The Name is required.'.
        /// </summary>
        public static string DynamicResourceNameRequired {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceNameRequired, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The Value is required.'.
        /// </summary>
        public static string DynamicResourceValueRequired {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicResourceValueRequired, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Setting'.
        /// </summary>
        public static string DynamicSettingEntityTypeDisplayName {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicSettingEntityTypeDisplayName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'DynamicSetting'.
        /// </summary>
        public static string DynamicSettingExportFileName {
            get {
                return ResourceManager.GetString(ResourceNames.DynamicSettingExportFileName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceDuplicateName'.
            /// </summary>
            public const string DynamicResourceDuplicateName = "DynamicResourceDuplicateName";
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceDuplicateValue'.
            /// </summary>
            public const string DynamicResourceDuplicateValue = "DynamicResourceDuplicateValue";
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceEntityTypeDisplayName'.
            /// </summary>
            public const string DynamicResourceEntityTypeDisplayName = "DynamicResourceEntityTypeDisplayName";
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceExportFileName'.
            /// </summary>
            public const string DynamicResourceExportFileName = "DynamicResourceExportFileName";
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceNameRequired'.
            /// </summary>
            public const string DynamicResourceNameRequired = "DynamicResourceNameRequired";
            
            /// <summary>
            /// Stores the resource name 'DynamicResourceValueRequired'.
            /// </summary>
            public const string DynamicResourceValueRequired = "DynamicResourceValueRequired";
            
            /// <summary>
            /// Stores the resource name 'DynamicSettingEntityTypeDisplayName'.
            /// </summary>
            public const string DynamicSettingEntityTypeDisplayName = "DynamicSettingEntityTypeDisplayName";
            
            /// <summary>
            /// Stores the resource name 'DynamicSettingExportFileName'.
            /// </summary>
            public const string DynamicSettingExportFileName = "DynamicSettingExportFileName";
        }
    }
}
