//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class FunctionOperationResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a FunctionOperationResources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public FunctionOperationResources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.Resources.FunctionOperationResourc" +
                                        "es", typeof(FunctionOperationResources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Transfer Generic Module'.
        /// </summary>
        public static string GenericDataTransferOperationGroup {
            get {
                return ResourceManager.GetString(ResourceNames.GenericDataTransferOperationGroup, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Dynamic Resources'.
        /// </summary>
        public static string ManageDynamicResources {
            get {
                return ResourceManager.GetString(ResourceNames.ManageDynamicResources, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Dynamic Settings'.
        /// </summary>
        public static string ManageDynamicSettings {
            get {
                return ResourceManager.GetString(ResourceNames.ManageDynamicSettings, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View DT Client Notifications'.
        /// </summary>
        public static string ViewClientNotifications {
            get {
                return ResourceManager.GetString(ResourceNames.ViewClientNotifications, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View DT Generic Notifications'.
        /// </summary>
        public static string ViewGenericNotifications {
            get {
                return ResourceManager.GetString(ResourceNames.ViewGenericNotifications, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View DT Generic Notifications Definitions'.
        /// </summary>
        public static string ViewGenericNotificationsDefinitions {
            get {
                return ResourceManager.GetString(ResourceNames.ViewGenericNotificationsDefinitions, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View DT Manage Notifications Generation'.
        /// </summary>
        public static string ViewManageNotificationsGeneration {
            get {
                return ResourceManager.GetString(ResourceNames.ViewManageNotificationsGeneration, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'GenericDataTransferOperationGroup'.
            /// </summary>
            public const string GenericDataTransferOperationGroup = "GenericDataTransferOperationGroup";
            
            /// <summary>
            /// Stores the resource name 'ManageDynamicResources'.
            /// </summary>
            public const string ManageDynamicResources = "ManageDynamicResources";
            
            /// <summary>
            /// Stores the resource name 'ManageDynamicSettings'.
            /// </summary>
            public const string ManageDynamicSettings = "ManageDynamicSettings";
            
            /// <summary>
            /// Stores the resource name 'ViewClientNotifications'.
            /// </summary>
            public const string ViewClientNotifications = "ViewClientNotifications";
            
            /// <summary>
            /// Stores the resource name 'ViewGenericNotifications'.
            /// </summary>
            public const string ViewGenericNotifications = "ViewGenericNotifications";
            
            /// <summary>
            /// Stores the resource name 'ViewGenericNotificationsDefinitions'.
            /// </summary>
            public const string ViewGenericNotificationsDefinitions = "ViewGenericNotificationsDefinitions";
            
            /// <summary>
            /// Stores the resource name 'ViewManageNotificationsGeneration'.
            /// </summary>
            public const string ViewManageNotificationsGeneration = "ViewManageNotificationsGeneration";
        }
    }
}
