// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;
using Kernel.Audit.Entities;
using Kernel.DDD.Domain.Events;
using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Events.Controllers
{
    /// <summary>
    /// The generated side of DTGenericEventsController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Events")]
   // old routes -- [Route("api/IRT/v1/DTGeneric/Events")]
    [Produces("application/json")]
    public partial class DTGenericEventsController : EventsController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public DTGenericEventsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

        private ActionResult GetEventsResult(DateTime? from, DateTime? to, string typeName)
        {
            ActionResult response;

            var events = GetEvents(from, to, typeName);

            response = Ok(events);
            return response;
        }

        private IEnumerable<IEvent> GetEvents(DateTime? from, DateTime? to, string typeName)
        {
            return GetEventSqlViews(from, to, typeName).Select(e => e.ToEvent());
        }

        private IEnumerable<EventSqlView> GetEventSqlViews(DateTime? from, DateTime? to, string typeName)
        {
            if (from == null)
            {
                from = DateTime.MinValue;
            }

            if (to == null)
            {
                to = DateTime.MaxValue;
            }

            Func<EventSqlView, bool> predicate = (EventSqlView pEvent) => pEvent.TypeName.Equals(typeName) && pEvent.OccurredDateTimeUtc > from && pEvent.OccurredDateTimeUtc <= to;
            var results = DbContext.Set<EventSqlView>().Where(predicate);
            return results;
        }
    }
}
