// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcDataTransferStudySettings))]
    public class GenericEdcDataTransferStudySettingsNullTypeDto
    {
        public System.String StudyId { get; set; }
        public System.String EnableRaveErrorNotification { get; set; }
        public System.String EnableVeevaErrorNotification { get; set; }
        public System.String ExcludeFromScheduledVisits { get; set; }
        public System.String UnscheduledVisits { get; set; }
        public System.String ReplacementVisits { get; set; }
        public System.String ScreenFailVisits { get; set; }
        public System.String InformedConsentVisits { get; set; }
    }

    public class GenericEdcDataTransferStudySettingsNullTypeDtoInput
    {
        public System.String EnableRaveErrorNotification { get; set; }
        public System.String EnableVeevaErrorNotification { get; set; }
        public System.String ExcludeFromScheduledVisits { get; set; }
        public System.String UnscheduledVisits { get; set; }
        public System.String ReplacementVisits { get; set; }
        public System.String ScreenFailVisits { get; set; }
        public System.String InformedConsentVisits { get; set; }
    }
}