// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings))]
    public class GenericEdcNotificationDefinitionSettingsNullTypeDto
    {
        public System.String NotificationDefinitionId { get; set; }
        public System.String FormRepeatKeysEnabled { get; set; }
        public System.String FormRepeatKeyFormat { get; set; }
        public System.String StudyEventRepeatKeysEnabled { get; set; }
        public System.String StudyEventRepeatKeyFormat { get; set; }
        public System.String FirstStudyEventRepeatKeyFormat { get; set; }
        public System.String AllowStudyEventRepeatKeyReuse { get; set; }
        public System.String StudyEventRepeatKeyBasis { get; set; }
        public System.String StudyEventRepeatKeyCounterInitialValue { get; set; }
        public System.String ItemGroupRepeatKeysEnabled { get; set; }
        public System.String ItemGroupRepeatKeyFormat { get; set; }
        public System.String FirstItemGroupRepeatKeyFormat { get; set; }
        public System.String AllowItemGroupRepeatKeyReuse { get; set; }
        public System.String ItemGroupRepeatKeyCounterInitialValue { get; set; }
        public System.String ItemGroupRepeatKeyInsertTransactionType { get; set; }
        public System.String ItemGroupRepeatKeyUpdateTransactionType { get; set; }
        public System.String ItemGroupRepeatKeyRemoveTransactionType { get; set; }
        public System.String ExistingItemGroupRepeatKeys { get; set; }
        public System.String ItemGroupRepeatKeyCountSkippedVisits { get; set; }
        public System.String ItemGroupRepeatKeysDrugCodesToExclude { get; set; }
        public System.String ItemGroupRepeatKeysVisitsToInclude { get; set; }
        public System.String ItemGroupRepeatKeysVisitsToExclude { get; set; }
        public System.String ItemGroupRepeatKeyBasis { get; set; }
        public System.String ItemGroupRepeatKeyCounterBasis { get; set; }
        public System.String ItemGroupRepeatKeyUnscheduledVisitsStrategy { get; set; }
        public System.String ItemGroupRepeatKeyReplacementVisitsStrategy { get; set; }
        public System.String ItemGroupRepeatKeyOverwriteReplacedDrug { get; set; }
        public System.String ItemGroupRepeatKeyResendReplacedDrugOnBackout { get; set; }
        public System.String ItemGroupRepeatKeyOverwriteManuallyReplacedDrug { get; set; }
        public System.String ItemGroupRepeatKeyResendManuallyReplacedDrugOnDelete { get; set; }
    }

    public class GenericEdcNotificationDefinitionSettingsNullTypeDtoInput
    {
        public System.String FormRepeatKeysEnabled { get; set; }
        public System.String FormRepeatKeyFormat { get; set; }
        public System.String StudyEventRepeatKeysEnabled { get; set; }
        public System.String StudyEventRepeatKeyFormat { get; set; }
        public System.String FirstStudyEventRepeatKeyFormat { get; set; }
        public System.String AllowStudyEventRepeatKeyReuse { get; set; }
        public System.String StudyEventRepeatKeyBasis { get; set; }
        public System.String StudyEventRepeatKeyCounterInitialValue { get; set; }
        public System.String ItemGroupRepeatKeysEnabled { get; set; }
        public System.String ItemGroupRepeatKeyFormat { get; set; }
        public System.String FirstItemGroupRepeatKeyFormat { get; set; }
        public System.String AllowItemGroupRepeatKeyReuse { get; set; }
        public System.String ItemGroupRepeatKeyCounterInitialValue { get; set; }
        public System.String ItemGroupRepeatKeyInsertTransactionType { get; set; }
        public System.String ItemGroupRepeatKeyUpdateTransactionType { get; set; }
        public System.String ItemGroupRepeatKeyRemoveTransactionType { get; set; }
        public System.String ExistingItemGroupRepeatKeys { get; set; }
        public System.String ItemGroupRepeatKeyCountSkippedVisits { get; set; }
        public System.String ItemGroupRepeatKeysDrugCodesToExclude { get; set; }
        public System.String ItemGroupRepeatKeysVisitsToInclude { get; set; }
        public System.String ItemGroupRepeatKeysVisitsToExclude { get; set; }
        public System.String ItemGroupRepeatKeyBasis { get; set; }
        public System.String ItemGroupRepeatKeyCounterBasis { get; set; }
        public System.String ItemGroupRepeatKeyUnscheduledVisitsStrategy { get; set; }
        public System.String ItemGroupRepeatKeyReplacementVisitsStrategy { get; set; }
        public System.String ItemGroupRepeatKeyOverwriteReplacedDrug { get; set; }
        public System.String ItemGroupRepeatKeyResendReplacedDrugOnBackout { get; set; }
        public System.String ItemGroupRepeatKeyOverwriteManuallyReplacedDrug { get; set; }
        public System.String ItemGroupRepeatKeyResendManuallyReplacedDrugOnDelete { get; set; }
    }
}