// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using Api.Irt.Domain;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts
{
    [ExtendedPropertiesTypeRelation(typeof(IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcVisitSettings))]
    public class GenericEdcVisitSettingsNullTypeDto
    {
        public System.String VisitId { get; set; }
        public System.String VisitMapping { get; set; }
        public System.String FormRepeatKeyFormat { get; set; }
        public System.String StudyEventRepeatKeyFormat { get; set; }
        public System.String FirstStudyEventRepeatKeyFormat { get; set; }
        public System.String ItemGroupRepeatKeyFormat { get; set; }
        public System.String FirstItemGroupRepeatKeyFormat { get; set; }
    }

    public class GenericEdcVisitSettingsNullTypeDtoInput
    {
        public System.String VisitMapping { get; set; }
        public System.String FormRepeatKeyFormat { get; set; }
        public System.String StudyEventRepeatKeyFormat { get; set; }
        public System.String FirstStudyEventRepeatKeyFormat { get; set; }
        public System.String ItemGroupRepeatKeyFormat { get; set; }
        public System.String FirstItemGroupRepeatKeyFormat { get; set; }
    }
}