//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.Aggregates.DynamicSetting.Validations.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class ValidationResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a ValidationResources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ValidationResources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.Aggregates.DynamicSetting.Validati" +
                                        "ons.Resources.ValidationResources", typeof(ValidationResources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'EntityTypeName cannot be empty.'.
        /// </summary>
        public static string EmptyEntityTypeName {
            get {
                return ResourceManager.GetString(ResourceNames.EmptyEntityTypeName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ExtendedPropertyName cannot be empty.'.
        /// </summary>
        public static string EmptyExtendedPropertyName {
            get {
                return ResourceManager.GetString(ResourceNames.EmptyExtendedPropertyName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name cannot be empty.'.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString(ResourceNames.EmptyName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Setting with the same ExtendedPropertyName already exists.'.
        /// </summary>
        public static string SameExtendedPropertyName {
            get {
                return ResourceManager.GetString(ResourceNames.SameExtendedPropertyName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Setting with the same Id already exists.'.
        /// </summary>
        public static string SameId {
            get {
                return ResourceManager.GetString(ResourceNames.SameId, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dynamic Setting with the same Name already exists.'.
        /// </summary>
        public static string SameName {
            get {
                return ResourceManager.GetString(ResourceNames.SameName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'EntityTypeName is not Valid.'.
        /// </summary>
        public static string ValidEntityTypeName {
            get {
                return ResourceManager.GetString(ResourceNames.ValidEntityTypeName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ExtendedPropertyName is not a valid property name.'.
        /// </summary>
        public static string ValidExtendedPropertyName {
            get {
                return ResourceManager.GetString(ResourceNames.ValidExtendedPropertyName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'EmptyEntityTypeName'.
            /// </summary>
            public const string EmptyEntityTypeName = "EmptyEntityTypeName";
            
            /// <summary>
            /// Stores the resource name 'EmptyExtendedPropertyName'.
            /// </summary>
            public const string EmptyExtendedPropertyName = "EmptyExtendedPropertyName";
            
            /// <summary>
            /// Stores the resource name 'EmptyName'.
            /// </summary>
            public const string EmptyName = "EmptyName";
            
            /// <summary>
            /// Stores the resource name 'SameExtendedPropertyName'.
            /// </summary>
            public const string SameExtendedPropertyName = "SameExtendedPropertyName";
            
            /// <summary>
            /// Stores the resource name 'SameId'.
            /// </summary>
            public const string SameId = "SameId";
            
            /// <summary>
            /// Stores the resource name 'SameName'.
            /// </summary>
            public const string SameName = "SameName";
            
            /// <summary>
            /// Stores the resource name 'ValidEntityTypeName'.
            /// </summary>
            public const string ValidEntityTypeName = "ValidEntityTypeName";
            
            /// <summary>
            /// Stores the resource name 'ValidExtendedPropertyName'.
            /// </summary>
            public const string ValidExtendedPropertyName = "ValidExtendedPropertyName";
        }
    }
}
