//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class NotificationDefinitions {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a NotificationDefinitions object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public NotificationDefinitions() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.Resources.Notifi" +
                                        "cationDefinitions", typeof(NotificationDefinitions).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Form Error'.
        /// </summary>
        public static string ErrorForm {
            get {
                return ResourceManager.GetString(ResourceNames.ErrorForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error Forms Summary'.
        /// </summary>
        public static string ErrorSummaryForm {
            get {
                return ResourceManager.GetString(ResourceNames.ErrorSummaryForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic Runtime Notification - {0}'.
        /// </summary>
        public static string GenericRuntimeNotification {
            get {
                return ResourceManager.GetString(ResourceNames.GenericRuntimeNotification, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic Subject Form'.
        /// </summary>
        public static string GenericSubjectForm {
            get {
                return ResourceManager.GetString(ResourceNames.GenericSubjectForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Demographics Form'.
        /// </summary>
        public static string RaveClientDemographicsForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientDemographicsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Drug Dispensation Form'.
        /// </summary>
        public static string RaveClientDrugDispensationForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientDrugDispensationForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Edc Get Data Request'.
        /// </summary>
        public static string RaveClientEdcReceivedData {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientEdcReceivedData, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Enrollment Form'.
        /// </summary>
        public static string RaveClientEnrollmentForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientEnrollmentForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Randomization Form'.
        /// </summary>
        public static string RaveClientRandomizationForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientRandomizationForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Screen Failed Form'.
        /// </summary>
        public static string RaveClientScreenFailedForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientScreenFailedForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Screening Form'.
        /// </summary>
        public static string RaveClientScreeningForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientScreeningForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Client Subject Form'.
        /// </summary>
        public static string RaveClientSubjectForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveClientSubjectForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Form Error'.
        /// </summary>
        public static string RaveErrorForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveErrorForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Error Forms List'.
        /// </summary>
        public static string RaveErrorFormsList {
            get {
                return ResourceManager.GetString(ResourceNames.RaveErrorFormsList, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Demographics Form'.
        /// </summary>
        public static string RaveGenericDemographicsForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericDemographicsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Drug Dispensation Form'.
        /// </summary>
        public static string RaveGenericDrugDispensationForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericDrugDispensationForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Enrollment Form'.
        /// </summary>
        public static string RaveGenericEnrollmentForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericEnrollmentForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Randomization Form'.
        /// </summary>
        public static string RaveGenericRandomizationForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericRandomizationForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Screen Failed Form'.
        /// </summary>
        public static string RaveGenericScreenFailedForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericScreenFailedForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Screening Form'.
        /// </summary>
        public static string RaveGenericScreeningForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericScreeningForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave Generic Subject Form'.
        /// </summary>
        public static string RaveGenericSubjectForm {
            get {
                return ResourceManager.GetString(ResourceNames.RaveGenericSubjectForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Authorization Form'.
        /// </summary>
        public static string VeevaClientAuthorizationForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientAuthorizationForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Combination Form Data Update Form'.
        /// </summary>
        public static string VeevaClientCombinationFormDataUpdateForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientCombinationFormDataUpdateForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Create Casebook Form'.
        /// </summary>
        public static string VeevaClientCreateCasebookForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientCreateCasebookForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Create Event Groups Form'.
        /// </summary>
        public static string VeevaClientCreateEventGroupsForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientCreateEventGroupsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Create Forms Form'.
        /// </summary>
        public static string VeevaClientCreateFormsForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientCreateFormsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Edit Submitted Form Form'.
        /// </summary>
        public static string VeevaClientEditSubmittedFormForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientEditSubmittedFormForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Set Event As Did Not Occur  Form'.
        /// </summary>
        public static string VeevaClientSetEventAsDidNotOccurForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientSetEventAsDidNotOccurForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Set Event Date Form'.
        /// </summary>
        public static string VeevaClientSetEventDateForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientSetEventDateForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Set Item Value Form'.
        /// </summary>
        public static string VeevaClientSetItemValueForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientSetItemValueForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Set Subject Status Form'.
        /// </summary>
        public static string VeevaClientSetSubjectStatusForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientSetSubjectStatusForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Submit Form Form'.
        /// </summary>
        public static string VeevaClientSubmitFormForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientSubmitFormForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Unset Subject Status Form'.
        /// </summary>
        public static string VeevaClientUnsetSubjectStatusForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientUnsetSubjectStatusForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Upsert Event Groups Form'.
        /// </summary>
        public static string VeevaClientUpsertEventGroupsForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientUpsertEventGroupsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Client Upsert Forms Form'.
        /// </summary>
        public static string VeevaClientUpsertFormsForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaClientUpsertFormsForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Form Error'.
        /// </summary>
        public static string VeevaErrorForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaErrorForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Error Forms List'.
        /// </summary>
        public static string VeevaErrorFormsList {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaErrorFormsList, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Generic Screening Form'.
        /// </summary>
        public static string VeevaGenericScreeningForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaGenericScreeningForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Self Transform Create Casebook Form'.
        /// </summary>
        public static string VeevaSelfTransformCreateCasebookForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaSelfTransformCreateCasebookForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva Self Transform Subject Form'.
        /// </summary>
        public static string VeevaSelfTransformSubjectForm {
            get {
                return ResourceManager.GetString(ResourceNames.VeevaSelfTransformSubjectForm, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Generic Runtime Notification - {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GenericRuntimeNotificationFormat(object arg0) {
            return string.Format(_resourceCulture, GenericRuntimeNotification, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ErrorForm'.
            /// </summary>
            public const string ErrorForm = "ErrorForm";
            
            /// <summary>
            /// Stores the resource name 'ErrorSummaryForm'.
            /// </summary>
            public const string ErrorSummaryForm = "ErrorSummaryForm";
            
            /// <summary>
            /// Stores the resource name 'GenericRuntimeNotification'.
            /// </summary>
            public const string GenericRuntimeNotification = "GenericRuntimeNotification";
            
            /// <summary>
            /// Stores the resource name 'GenericSubjectForm'.
            /// </summary>
            public const string GenericSubjectForm = "GenericSubjectForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientDemographicsForm'.
            /// </summary>
            public const string RaveClientDemographicsForm = "RaveClientDemographicsForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientDrugDispensationForm'.
            /// </summary>
            public const string RaveClientDrugDispensationForm = "RaveClientDrugDispensationForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientEdcReceivedData'.
            /// </summary>
            public const string RaveClientEdcReceivedData = "RaveClientEdcReceivedData";
            
            /// <summary>
            /// Stores the resource name 'RaveClientEnrollmentForm'.
            /// </summary>
            public const string RaveClientEnrollmentForm = "RaveClientEnrollmentForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientRandomizationForm'.
            /// </summary>
            public const string RaveClientRandomizationForm = "RaveClientRandomizationForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientScreenFailedForm'.
            /// </summary>
            public const string RaveClientScreenFailedForm = "RaveClientScreenFailedForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientScreeningForm'.
            /// </summary>
            public const string RaveClientScreeningForm = "RaveClientScreeningForm";
            
            /// <summary>
            /// Stores the resource name 'RaveClientSubjectForm'.
            /// </summary>
            public const string RaveClientSubjectForm = "RaveClientSubjectForm";
            
            /// <summary>
            /// Stores the resource name 'RaveErrorForm'.
            /// </summary>
            public const string RaveErrorForm = "RaveErrorForm";
            
            /// <summary>
            /// Stores the resource name 'RaveErrorFormsList'.
            /// </summary>
            public const string RaveErrorFormsList = "RaveErrorFormsList";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericDemographicsForm'.
            /// </summary>
            public const string RaveGenericDemographicsForm = "RaveGenericDemographicsForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericDrugDispensationForm'.
            /// </summary>
            public const string RaveGenericDrugDispensationForm = "RaveGenericDrugDispensationForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericEnrollmentForm'.
            /// </summary>
            public const string RaveGenericEnrollmentForm = "RaveGenericEnrollmentForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericRandomizationForm'.
            /// </summary>
            public const string RaveGenericRandomizationForm = "RaveGenericRandomizationForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericScreenFailedForm'.
            /// </summary>
            public const string RaveGenericScreenFailedForm = "RaveGenericScreenFailedForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericScreeningForm'.
            /// </summary>
            public const string RaveGenericScreeningForm = "RaveGenericScreeningForm";
            
            /// <summary>
            /// Stores the resource name 'RaveGenericSubjectForm'.
            /// </summary>
            public const string RaveGenericSubjectForm = "RaveGenericSubjectForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientAuthorizationForm'.
            /// </summary>
            public const string VeevaClientAuthorizationForm = "VeevaClientAuthorizationForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientCombinationFormDataUpdateForm'.
            /// </summary>
            public const string VeevaClientCombinationFormDataUpdateForm = "VeevaClientCombinationFormDataUpdateForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientCreateCasebookForm'.
            /// </summary>
            public const string VeevaClientCreateCasebookForm = "VeevaClientCreateCasebookForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientCreateEventGroupsForm'.
            /// </summary>
            public const string VeevaClientCreateEventGroupsForm = "VeevaClientCreateEventGroupsForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientCreateFormsForm'.
            /// </summary>
            public const string VeevaClientCreateFormsForm = "VeevaClientCreateFormsForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientEditSubmittedFormForm'.
            /// </summary>
            public const string VeevaClientEditSubmittedFormForm = "VeevaClientEditSubmittedFormForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientSetEventAsDidNotOccurForm'.
            /// </summary>
            public const string VeevaClientSetEventAsDidNotOccurForm = "VeevaClientSetEventAsDidNotOccurForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientSetEventDateForm'.
            /// </summary>
            public const string VeevaClientSetEventDateForm = "VeevaClientSetEventDateForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientSetItemValueForm'.
            /// </summary>
            public const string VeevaClientSetItemValueForm = "VeevaClientSetItemValueForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientSetSubjectStatusForm'.
            /// </summary>
            public const string VeevaClientSetSubjectStatusForm = "VeevaClientSetSubjectStatusForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientSubmitFormForm'.
            /// </summary>
            public const string VeevaClientSubmitFormForm = "VeevaClientSubmitFormForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientUnsetSubjectStatusForm'.
            /// </summary>
            public const string VeevaClientUnsetSubjectStatusForm = "VeevaClientUnsetSubjectStatusForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientUpsertEventGroupsForm'.
            /// </summary>
            public const string VeevaClientUpsertEventGroupsForm = "VeevaClientUpsertEventGroupsForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaClientUpsertFormsForm'.
            /// </summary>
            public const string VeevaClientUpsertFormsForm = "VeevaClientUpsertFormsForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaErrorForm'.
            /// </summary>
            public const string VeevaErrorForm = "VeevaErrorForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaErrorFormsList'.
            /// </summary>
            public const string VeevaErrorFormsList = "VeevaErrorFormsList";
            
            /// <summary>
            /// Stores the resource name 'VeevaGenericScreeningForm'.
            /// </summary>
            public const string VeevaGenericScreeningForm = "VeevaGenericScreeningForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaSelfTransformCreateCasebookForm'.
            /// </summary>
            public const string VeevaSelfTransformCreateCasebookForm = "VeevaSelfTransformCreateCasebookForm";
            
            /// <summary>
            /// Stores the resource name 'VeevaSelfTransformSubjectForm'.
            /// </summary>
            public const string VeevaSelfTransformSubjectForm = "VeevaSelfTransformSubjectForm";
        }
    }
}
