// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Api.Irt.Shared;
using Frameworks.ExtendedProperties.Configuration;
using Frameworks.ExtendedProperties.Registries;
using Frameworks.ExtendedProperties.Services.Interfaces;
using IRT.Domain;
using IRT.Domain.ViewsSql.Study;
using IRT.Domain.ViewsSql.User;
using Kernel.AspNetMvc.Security.Services;
using Kernel.DDD.Dispatching;
using Unity;
using Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.OData.Query;
using Api.Irt.Common;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Controllers
{
    [Produces("application/json")]
    //
    //  Authorization Required : Guid.Parse("94632bb7-f34d-4e93-af77-eddd9c88f3c6")
    //
    public partial class DynamicResourceExtendedPropertiesCrudController : ExtendedPropertiesApiController
    {
        public DynamicResourceExtendedPropertiesCrudController(
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext,
            ICommandBus commandBus,
            IContextService<StudySqlView, UserSqlView> contextService,
            IExtendedPropertiesFunctionConfigurator functionConfigurator,
            IExtendedPropertiesRegistry extendedPropertiesRegistry,
            IEntityDataService entityDataService) : base(
                httpContextAccessor,
                unityContainer,
                dbContext,
                commandBus,
                contextService,
                functionConfigurator,
                extendedPropertiesRegistry,
                entityDataService,
                Guid.Parse("94632bb7-f34d-4e93-af77-eddd9c88f3c6"))
        {
    
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties")]
        [HttpGet]
        [EnableQuery(MaxExpansionDepth=15)]
        [Produces(typeof(IEnumerable<DynamicResourceNullTypeDto>))]
        public ActionResult ReadExtendedProperties()
        {
            return ReadExtendedPropertiesCrudWithDefault<DynamicResourceNullTypeDto, IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource>(OperationId, "Kernel.Globalization.Entities.ResourceSqlView", "ResourceId", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties/create")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult CreateExtendedProperties(
            DynamicResourceNullTypeDto value)
        {
            return CreateExtendedPropertiesCrud(OperationId, "Kernel.Globalization.Entities.ResourceSqlView", value.ResourceId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource", value, "ResourceId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties/update")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult UpdateExtendedProperties(
            DynamicResourceNullTypeDto value)
        {
            return UpdateExtendedPropertiesCrud(OperationId, "Kernel.Globalization.Entities.ResourceSqlView", value.ResourceId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource", value, "ResourceId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties/delete")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult DeleteExtendedProperties(
            DynamicResourceNullTypeDto value)
        {
            return DeleteExtendedPropertiesCrud(OperationId, "Kernel.Globalization.Entities.ResourceSqlView", value.ResourceId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource", value, "ResourceId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties/export")]
        [HttpGet]
        [Produces("text/csv")]
        public ActionResult ExportExtendedProperties()
        {
            return ExportExtendedPropertiesCrud<DynamicResourceNullTypeDto>(OperationId, "Kernel.Globalization.Entities.ResourceSqlView", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource", "ResourceId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/dynamic-resource/extended-properties/import")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult ImportExtendedProperties(IEnumerable<IFormFile> importFiles)
        {
            return ImportExtendedPropertiesCrud<DynamicResourceNullTypeDto>(importFiles, OperationId, "Kernel.Globalization.Entities.ResourceSqlView", "ResourceId", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.Resource.DynamicResource");
        }
        
    }
}