// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Api.Irt.Shared;
using Frameworks.ExtendedProperties.Configuration;
using Frameworks.ExtendedProperties.Registries;
using Frameworks.ExtendedProperties.Services.Interfaces;
using IRT.Domain;
using IRT.Domain.ViewsSql.Study;
using IRT.Domain.ViewsSql.User;
using Kernel.AspNetMvc.Security.Services;
using Kernel.DDD.Dispatching;
using Unity;
using Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.OData.Query;
using Api.Irt.Common;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Controllers
{
    [Produces("application/json")]
    //
    //  Authorization Required : Guid.Parse("94632bb7-f34d-4e93-af77-eddd9c88f3c6")
    //
    public partial class NotificationGenerationSettingsExtendedPropertiesCrudController : ExtendedPropertiesApiController
    {
        public NotificationGenerationSettingsExtendedPropertiesCrudController(
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext,
            ICommandBus commandBus,
            IContextService<StudySqlView, UserSqlView> contextService,
            IExtendedPropertiesFunctionConfigurator functionConfigurator,
            IExtendedPropertiesRegistry extendedPropertiesRegistry,
            IEntityDataService entityDataService) : base(
                httpContextAccessor,
                unityContainer,
                dbContext,
                commandBus,
                contextService,
                functionConfigurator,
                extendedPropertiesRegistry,
                entityDataService,
                Guid.Parse("94632bb7-f34d-4e93-af77-eddd9c88f3c6"))
        {
    
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties")]
        [HttpGet]
        [EnableQuery(MaxExpansionDepth=15)]
        [Produces(typeof(IEnumerable<NotificationGenerationSettingsNullTypeDto>))]
        public ActionResult ReadExtendedProperties()
        {
            return ReadExtendedPropertiesCrudWithDefault<NotificationGenerationSettingsNullTypeDto, IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings>(OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", "EntityId", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties/create")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult CreateExtendedProperties(
            NotificationGenerationSettingsNullTypeDto value)
        {
            return CreateExtendedPropertiesCrud(OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", value.EntityId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings", value, "EntityId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties/update")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult UpdateExtendedProperties(
            NotificationGenerationSettingsNullTypeDto value)
        {
            return UpdateExtendedPropertiesCrud(OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", value.EntityId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings", value, "EntityId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties/delete")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult DeleteExtendedProperties(
            NotificationGenerationSettingsNullTypeDto value)
        {
            return DeleteExtendedPropertiesCrud(OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", value.EntityId.ToString(), "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings", value, "EntityId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties/export")]
        [HttpGet]
        [Produces("text/csv")]
        public ActionResult ExportExtendedProperties()
        {
            return ExportExtendedPropertiesCrud<NotificationGenerationSettingsNullTypeDto>(OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings", "EntityId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT : ExtendedProperties : Data-transfer-generic" })]
        [Route("/api/irt/v1/data-transfer-generic/notification-generation-settings/notification-generation-settings/extended-properties/import")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult ImportExtendedProperties(IEnumerable<IFormFile> importFiles)
        {
            return ImportExtendedPropertiesCrud<NotificationGenerationSettingsNullTypeDto>(importFiles, OperationId, "IRT.Domain.ViewsSql.ExtendedProperty.EntitySqlView", "EntityId", "IRT.Modules.DataTransfer.Generic.Domain.ValueObjects.StudySettings.NotificationGenerationSettings");
        }
        
    }
}