//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Controllers.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2024 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericNotificationsController {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericNotificationsController object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericNotificationsController() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Controllers.Res" +
                                        "ources.GenericNotificationsController", typeof(GenericNotificationsController).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generated'.
        /// </summary>
        public static string NotificationStatusGenerated {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationStatusGenerated, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Pending'.
        /// </summary>
        public static string NotificationStatusPending {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationStatusPending, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Received'.
        /// </summary>
        public static string NotificationStatusReceived {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationStatusReceived, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Sent'.
        /// </summary>
        public static string NotificationStatusSent {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationStatusSent, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Notification was successfully re-transmitted by email.'.
        /// </summary>
        public static string RetransmitSuccesMessage {
            get {
                return ResourceManager.GetString(ResourceNames.RetransmitSuccesMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'NotificationStatusGenerated'.
            /// </summary>
            public const string NotificationStatusGenerated = "NotificationStatusGenerated";
            
            /// <summary>
            /// Stores the resource name 'NotificationStatusPending'.
            /// </summary>
            public const string NotificationStatusPending = "NotificationStatusPending";
            
            /// <summary>
            /// Stores the resource name 'NotificationStatusReceived'.
            /// </summary>
            public const string NotificationStatusReceived = "NotificationStatusReceived";
            
            /// <summary>
            /// Stores the resource name 'NotificationStatusSent'.
            /// </summary>
            public const string NotificationStatusSent = "NotificationStatusSent";
            
            /// <summary>
            /// Stores the resource name 'RetransmitSuccesMessage'.
            /// </summary>
            public const string RetransmitSuccesMessage = "RetransmitSuccesMessage";
        }
    }
}
