//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Models.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class DynamicSettingCreateViewModel {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a DynamicSettingCreateViewModel object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DynamicSettingCreateViewModel() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Models.Resource" +
                                        "s.DynamicSettingCreateViewModel", typeof(DynamicSettingCreateViewModel).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Category'.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString(ResourceNames.Category, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Default Value'.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString(ResourceNames.DefaultValue, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Description'.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString(ResourceNames.Description, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'EntityType'.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString(ResourceNames.EntityType, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name'.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString(ResourceNames.Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Category'.
            /// </summary>
            public const string Category = "Category";
            
            /// <summary>
            /// Stores the resource name 'DefaultValue'.
            /// </summary>
            public const string DefaultValue = "DefaultValue";
            
            /// <summary>
            /// Stores the resource name 'Description'.
            /// </summary>
            public const string Description = "Description";
            
            /// <summary>
            /// Stores the resource name 'EntityType'.
            /// </summary>
            public const string EntityType = "EntityType";
            
            /// <summary>
            /// Stores the resource name 'Name'.
            /// </summary>
            public const string Name = "Name";
        }
    }
}
