//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Models.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2024 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericNotificationDefinitionViewModel {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericNotificationDefinitionViewModel object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericNotificationDefinitionViewModel() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Models.Resource" +
                                        "s.GenericNotificationDefinitionViewModel", typeof(GenericNotificationDefinitionViewModel).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Hop Endpoint '.
        /// </summary>
        public static string ApacheHopResourceEndpoint {
            get {
                return ResourceManager.GetString(ResourceNames.ApacheHopResourceEndpoint, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Body'.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString(ResourceNames.Body, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Data Service'.
        /// </summary>
        public static string DataService {
            get {
                return ResourceManager.GetString(ResourceNames.DataService, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name'.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString(ResourceNames.Name, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Type'.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationType, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Vendor'.
        /// </summary>
        public static string NotificationVendor {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationVendor, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Title'.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString(ResourceNames.Title, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Use Default Template Processor'.
        /// </summary>
        public static string UseDefaultTemplateProcessor {
            get {
                return ResourceManager.GetString(ResourceNames.UseDefaultTemplateProcessor, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ApacheHopResourceEndpoint'.
            /// </summary>
            public const string ApacheHopResourceEndpoint = "ApacheHopResourceEndpoint";
            
            /// <summary>
            /// Stores the resource name 'Body'.
            /// </summary>
            public const string Body = "Body";
            
            /// <summary>
            /// Stores the resource name 'DataService'.
            /// </summary>
            public const string DataService = "DataService";
            
            /// <summary>
            /// Stores the resource name 'Name'.
            /// </summary>
            public const string Name = "Name";
            
            /// <summary>
            /// Stores the resource name 'NotificationType'.
            /// </summary>
            public const string NotificationType = "NotificationType";
            
            /// <summary>
            /// Stores the resource name 'NotificationVendor'.
            /// </summary>
            public const string NotificationVendor = "NotificationVendor";
            
            /// <summary>
            /// Stores the resource name 'Title'.
            /// </summary>
            public const string Title = "Title";
            
            /// <summary>
            /// Stores the resource name 'UseDefaultTemplateProcessor'.
            /// </summary>
            public const string UseDefaultTemplateProcessor = "UseDefaultTemplateProcessor";
        }
    }
}
