// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using IRT.Domain;

using Kernel.DDD.Dispatching;

using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Commands.Controllers
{
    /// <summary>
    /// The generated side of DTGenericCommandsController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Commands")]
    // old routes -- [Route("api/IRT/v1/DTGeneric/Commands")]
    [Produces("application/json")]
    public partial class DTGenericCommandsController : CommandsController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public DTGenericCommandsController
        (
            ICommandBus commandBus,
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(commandBus, httpContextAccessor, unityContainer, dbContext)
        {
        }
        
        /// <summary>
        /// AcknowledgeClientNotification handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("AcknowledgeClientNotification")]
         [Route("api/irt/v1/data-transfer-generic/commands/acknowledge-client-notification")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult AcknowledgeClientNotification
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Commands.AcknowledgeClientNotification command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        
        /// <summary>
        /// CreateClientNotification handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("CreateClientNotification")]
         [Route("api/irt/v1/data-transfer-generic/commands/create-client-notification")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult CreateClientNotification
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Commands.CreateClientNotification command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        
        /// <summary>
        /// CreateDynamicSetting handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("CreateDynamicSetting")]
         [Route("api/irt/v1/data-transfer-generic/commands/create-dynamic-setting")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult CreateDynamicSetting
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.DynamicSetting.Commands.CreateDynamicSetting command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        
        /// <summary>
        /// MarkNotificationsAsSent handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("MarkNotificationsAsSent")]
         [Route("api/irt/v1/data-transfer-generic/commands/mark-notifications-as-sent")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult MarkNotificationsAsSent
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Commands.MarkNotificationsAsSent command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        
        /// <summary>
        /// ReceiveClientNotification handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("ReceiveClientNotification")]
         [Route("api/irt/v1/data-transfer-generic/commands/receive-client-notification")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult ReceiveClientNotification
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Commands.ReceiveClientNotification command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        
        /// <summary>
        /// UpdateClientNotification handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("UpdateClientNotification")]
         [Route("api/irt/v1/data-transfer-generic/commands/update-client-notification")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult UpdateClientNotification
        (
            IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Commands.UpdateClientNotification command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
    }
}
