// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.Extensions.Logging;
using Microsoft.OData.ModelBuilder;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Kernel.Globalization.Domain.Aggregates.LanguageAggregate.Enums;
using Kernel.OData.Contracts;

using Unity;
using Swashbuckle.AspNetCore.Annotations;


namespace Api.Irt.Modules.DataTransfer.Generic.EntityReads
{
    /// <summary>
    /// The standard controller for a GenericStudyEventRepeatKeyLastUsed entity.
    /// </summary>
    // old routes -- [Realm("DTGeneric > EntityReads")]
    // old routes -- [Route("IRT/v1/DTGeneric/IRT/GenericStudyEventRepeatKeyLastUsed")]
    [Produces("application/json")]
    public class GenericStudyEventRepeatKeyLastUsedEntityReadsController : EntityReadsController
    {
#region Constructors

        /// <summary>
        /// constructor
        /// </summary>
        public GenericStudyEventRepeatKeyLastUsedEntityReadsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

#endregion
        
        
        public static void RegisterModel(ODataModelBuilder builder)
        {
            builder.EntitySet<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView>("GenericStudyEventRepeatKeyLastUsedSqlView");
        }
        
#region Reads
        
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
         [Route("irt/v1/data-transfer-generic/i-r-t/generic-study-event-repeat-key-last-useds")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView>))]
        public ActionResult Get()
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView>().AsQueryable();
        
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        }
        /// <param name="RepeatKeyLastUsedId">RepeatKeyLastUsedId</param>
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
        // old routes -- [Route("{RepeatKeyLastUsedId}")]
         [Route("irt/v1/data-transfer-generic/i-r-t/generic-study-event-repeat-key-last-useds/{RepeatKeyLastUsedId}")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView))]
        public ActionResult Get
        (
              Guid RepeatKeyLastUsedId
        )
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView>().Where(entity => 
                     entity.RepeatKeyLastUsedId == RepeatKeyLastUsedId 
                );
        
                if (0 < result.Count())
                {
                    response = Ok(SingleResult.Create(result));
                }
                else
                {
                    response = NotFound();
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        } 
        
        /// <summary>
        /// Read an entity by the primary key, without embedded entities
        /// </summary>
        /// <param name="RepeatKeyLastUsedId">RepeatKeyLastUsedId</param>
        /// <returns>the entity if found, default otherwise</returns>
        protected IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView ReadByKeyWithoutEmbeds
        (
              Guid RepeatKeyLastUsedId
        )
        {
            IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView result = null;
            IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView read;
        
            try
            {
                read = ReadByKey
                (
                      RepeatKeyLastUsedId
                );
        
                if (read != null)
                {
                    result = new IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView()
                    {
                      RepeatKeyLastUsedId = read.RepeatKeyLastUsedId
                    , NotificationDefinitionId = read.NotificationDefinitionId
                    , SiteId = read.SiteId
                    , SubjectId = read.SubjectId
                    , SubjectVisitId = read.SubjectVisitId
                    , RepeatKeyLastUsed = read.RepeatKeyLastUsed
                    , ScheduledRepeatKeyLastUsed = read.ScheduledRepeatKeyLastUsed
                    , UnscheduledRepeatKeyLastUsed = read.UnscheduledRepeatKeyLastUsed
                    , ReplacementRepeatKeyLastUsed = read.ReplacementRepeatKeyLastUsed
                    , ScreenFailRepeatKeyLastUsed = read.ScreenFailRepeatKeyLastUsed
                    , InformedConsentRepeatKeyLastUsed = read.InformedConsentRepeatKeyLastUsed
                    };
                }
            }
            catch
            {
            }
        
            return result;
        }
        
#endregion
        
        
        /// <summary>
        /// Read an entity by the primary key
        /// </summary>
    /// <param name="RepeatKeyLastUsedId">RepeatKeyLastUsedId</param>
    /// <returns>the entity if found, default otherwise</returns>
    protected IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView ReadByKey
    (
          Guid RepeatKeyLastUsedId
    )
    {
        IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView result = null;

        try
        {
            result = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.StudyEvent.GenericStudyEventRepeatKeyLastUsedSqlView>().Where
            (s =>
                s.RepeatKeyLastUsedId.Equals(RepeatKeyLastUsedId)
            ).FirstOrDefault();
        }
        catch
        {
        }

        return result;
    }

    }

    /// <summary>
    /// input schema for the entity
    /// </summary>
    public class GenericStudyEventRepeatKeyLastUsedInput
    {
        /// <summary>
        /// RepeatKeyLastUsedId
        /// </summary>
        public System.Guid RepeatKeyLastUsedId {get; set;}
        
        /// <summary>
        /// NotificationDefinitionId
        /// </summary>
        public System.Guid NotificationDefinitionId {get; set;}
        
        /// <summary>
        /// SiteId
        /// </summary>
        public string SiteId {get; set;}
        
        /// <summary>
        /// SubjectId
        /// </summary>
        public System.Guid? SubjectId {get; set;}
        
        /// <summary>
        /// SubjectVisitId
        /// </summary>
        public System.Guid? SubjectVisitId {get; set;}
        
        /// <summary>
        /// RepeatKeyLastUsed
        /// </summary>
        public int? RepeatKeyLastUsed {get; set;}
        
        /// <summary>
        /// ScheduledRepeatKeyLastUsed
        /// </summary>
        public int? ScheduledRepeatKeyLastUsed {get; set;}
        
        /// <summary>
        /// UnscheduledRepeatKeyLastUsed
        /// </summary>
        public int? UnscheduledRepeatKeyLastUsed {get; set;}
        
        /// <summary>
        /// ReplacementRepeatKeyLastUsed
        /// </summary>
        public int? ReplacementRepeatKeyLastUsed {get; set;}
        
        /// <summary>
        /// ScreenFailRepeatKeyLastUsed
        /// </summary>
        public int? ScreenFailRepeatKeyLastUsed {get; set;}
        
        /// <summary>
        /// InformedConsentRepeatKeyLastUsed
        /// </summary>
        public int? InformedConsentRepeatKeyLastUsed {get; set;}
    }
}
