// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.Extensions.Logging;
using Microsoft.OData.ModelBuilder;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Kernel.Globalization.Domain.Aggregates.LanguageAggregate.Enums;
using Kernel.OData.Contracts;

using Unity;
using Swashbuckle.AspNetCore.Annotations;


namespace Api.Irt.Modules.DataTransfer.Generic.EntityReads
{
    /// <summary>
    /// The standard controller for a GenericItemGroupRepeatKey entity.
    /// </summary>
    // old routes -- [Realm("DTGeneric > EntityReads")]
    // old routes -- [Route("IRT/v1/DTGeneric/IRT/GenericItemGroupRepeatKey")]
    [Produces("application/json")]
    public class GenericItemGroupRepeatKeyEntityReadsController : EntityReadsController
    {
#region Constructors

        /// <summary>
        /// constructor
        /// </summary>
        public GenericItemGroupRepeatKeyEntityReadsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

#endregion
        
        
        public static void RegisterModel(ODataModelBuilder builder)
        {
            builder.EntitySet<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView>("GenericItemGroupRepeatKeySqlView");
        }
        
#region Reads
        
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
         [Route("irt/v1/data-transfer-generic/i-r-t/generic-item-group-repeat-keies")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView>))]
        public ActionResult Get()
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView>().AsQueryable();
        
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        }
        /// <param name="RepeatKeyId">RepeatKeyId</param>
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
        // old routes -- [Route("{RepeatKeyId}")]
         [Route("irt/v1/data-transfer-generic/i-r-t/generic-item-group-repeat-keies/{RepeatKeyId}")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView))]
        public ActionResult Get
        (
              Guid RepeatKeyId
        )
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView>().Where(entity => 
                     entity.RepeatKeyId == RepeatKeyId 
                );
        
                if (0 < result.Count())
                {
                    response = Ok(SingleResult.Create(result));
                }
                else
                {
                    response = NotFound();
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        } 
        
        /// <summary>
        /// Read an entity by the primary key, without embedded entities
        /// </summary>
        /// <param name="RepeatKeyId">RepeatKeyId</param>
        /// <returns>the entity if found, default otherwise</returns>
        protected IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView ReadByKeyWithoutEmbeds
        (
              Guid RepeatKeyId
        )
        {
            IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView result = null;
            IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView read;
        
            try
            {
                read = ReadByKey
                (
                      RepeatKeyId
                );
        
                if (read != null)
                {
                    result = new IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView()
                    {
                      RepeatKeyId = read.RepeatKeyId
                    , NotificationDefinitionId = read.NotificationDefinitionId
                    , SiteId = read.SiteId
                    , SubjectId = read.SubjectId
                    , SubjectVisitId = read.SubjectVisitId
                    , LogicalSubjectVisitId = read.LogicalSubjectVisitId
                    , VisitId = read.VisitId
                    , LogicalVisitId = read.LogicalVisitId
                    , DrugUnitId = read.DrugUnitId
                    , ReplacedDrugUnitId = read.ReplacedDrugUnitId
                    , DrugUnitIdToRestore = read.DrugUnitIdToRestore
                    , IsDrugUnitReplaced = read.IsDrugUnitReplaced
                    , IsSelfSupportDrugUnit = read.IsSelfSupportDrugUnit
                    , RepeatKey = read.RepeatKey
                    , TransactionType = read.TransactionType
                    };
                }
            }
            catch
            {
            }
        
            return result;
        }
        
#endregion
        
        
        /// <summary>
        /// Read an entity by the primary key
        /// </summary>
    /// <param name="RepeatKeyId">RepeatKeyId</param>
    /// <returns>the entity if found, default otherwise</returns>
    protected IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView ReadByKey
    (
          Guid RepeatKeyId
    )
    {
        IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView result = null;

        try
        {
            result = DbContext.Set<IRT.Modules.DataTransfer.Generic.Edc.Domain.SqlViews.RepeatKeys.ItemGroup.GenericItemGroupRepeatKeySqlView>().Where
            (s =>
                s.RepeatKeyId.Equals(RepeatKeyId)
            ).FirstOrDefault();
        }
        catch
        {
        }

        return result;
    }

    }

    /// <summary>
    /// input schema for the entity
    /// </summary>
    public class GenericItemGroupRepeatKeyInput
    {
        /// <summary>
        /// RepeatKeyId
        /// </summary>
        public System.Guid RepeatKeyId {get; set;}
        
        /// <summary>
        /// NotificationDefinitionId
        /// </summary>
        public System.Guid NotificationDefinitionId {get; set;}
        
        /// <summary>
        /// SiteId
        /// </summary>
        public string SiteId {get; set;}
        
        /// <summary>
        /// SubjectId
        /// </summary>
        public System.Guid? SubjectId {get; set;}
        
        /// <summary>
        /// SubjectVisitId
        /// </summary>
        public System.Guid? SubjectVisitId {get; set;}
        
        /// <summary>
        /// LogicalSubjectVisitId
        /// </summary>
        public System.Guid? LogicalSubjectVisitId {get; set;}
        
        /// <summary>
        /// VisitId
        /// </summary>
        public string VisitId {get; set;}
        
        /// <summary>
        /// LogicalVisitId
        /// </summary>
        public string LogicalVisitId {get; set;}
        
        /// <summary>
        /// DrugUnitId
        /// </summary>
        public string DrugUnitId {get; set;}
        
        /// <summary>
        /// ReplacedDrugUnitId
        /// </summary>
        public string ReplacedDrugUnitId {get; set;}
        
        /// <summary>
        /// DrugUnitIdToRestore
        /// </summary>
        public string DrugUnitIdToRestore {get; set;}
        
        /// <summary>
        /// IsDrugUnitReplaced
        /// </summary>
        public bool? IsDrugUnitReplaced {get; set;}
        
        /// <summary>
        /// IsSelfSupportDrugUnit
        /// </summary>
        public bool? IsSelfSupportDrugUnit {get; set;}
        
        /// <summary>
        /// RepeatKey
        /// </summary>
        public int? RepeatKey {get; set;}
        
        /// <summary>
        /// TransactionType
        /// </summary>
        public string TransactionType {get; set;}
    }
}
