//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Validators.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class ValidationResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a ValidationResources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ValidationResources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Val" +
                                        "idators.Resources.ValidationResources", typeof(ValidationResources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Body of a form cannot be empty.'.
        /// </summary>
        public static string EmptyBody {
            get {
                return ResourceManager.GetString(ResourceNames.EmptyBody, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Title of a form cannot be empty.'.
        /// </summary>
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString(ResourceNames.EmptyTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Number of failed submit attempts should be greater than or equal to zero.'.
        /// </summary>
        public static string FailedAtteptsError {
            get {
                return ResourceManager.GetString(ResourceNames.FailedAtteptsError, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Body of a form contains invalid format.'.
        /// </summary>
        public static string InvalidBody {
            get {
                return ResourceManager.GetString(ResourceNames.InvalidBody, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Notification not found'.
        /// </summary>
        public static string NotificationNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave notification with the same ID already exists.'.
        /// </summary>
        public static string SameID {
            get {
                return ResourceManager.GetString(ResourceNames.SameID, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject visit should refer the selected Subject'.
        /// </summary>
        public static string SubjectDoesntMatch {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectDoesntMatch, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject not found'.
        /// </summary>
        public static string SubjectNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Subject visit not found'.
        /// </summary>
        public static string SubjectVisitNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.SubjectVisitNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'EmptyBody'.
            /// </summary>
            public const string EmptyBody = "EmptyBody";
            
            /// <summary>
            /// Stores the resource name 'EmptyTitle'.
            /// </summary>
            public const string EmptyTitle = "EmptyTitle";
            
            /// <summary>
            /// Stores the resource name 'FailedAtteptsError'.
            /// </summary>
            public const string FailedAtteptsError = "FailedAtteptsError";
            
            /// <summary>
            /// Stores the resource name 'InvalidBody'.
            /// </summary>
            public const string InvalidBody = "InvalidBody";
            
            /// <summary>
            /// Stores the resource name 'NotificationNotFound'.
            /// </summary>
            public const string NotificationNotFound = "NotificationNotFound";
            
            /// <summary>
            /// Stores the resource name 'SameID'.
            /// </summary>
            public const string SameID = "SameID";
            
            /// <summary>
            /// Stores the resource name 'SubjectDoesntMatch'.
            /// </summary>
            public const string SubjectDoesntMatch = "SubjectDoesntMatch";
            
            /// <summary>
            /// Stores the resource name 'SubjectNotFound'.
            /// </summary>
            public const string SubjectNotFound = "SubjectNotFound";
            
            /// <summary>
            /// Stores the resource name 'SubjectVisitNotFound'.
            /// </summary>
            public const string SubjectVisitNotFound = "SubjectVisitNotFound";
        }
    }
}
