//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Properties {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Resources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Resources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Properties.Resources", typeof(Resources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Dynamic Resources'.
        /// </summary>
        public static string ManageDynamicResources_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ManageDynamicResources_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Dynamic Settings'.
        /// </summary>
        public static string ManageDynamicSettings_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ManageDynamicSettings_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Generic Notifications'.
        /// </summary>
        public static string ManageNotifications_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ManageNotifications_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic Notification Definition'.
        /// </summary>
        public static string NotificationDefinitionEntityTypeDisplayName {
            get {
                return ResourceManager.GetString(ResourceNames.NotificationDefinitionEntityTypeDisplayName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'NotificationsForms'.
        /// </summary>
        public static string SettingsExportFileName {
            get {
                return ResourceManager.GetString(ResourceNames.SettingsExportFileName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client Notifications'.
        /// </summary>
        public static string ViewClientNotifications_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ViewClientNotifications_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic Notifications'.
        /// </summary>
        public static string ViewGenericNotifications_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ViewGenericNotifications_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Notifications Generation'.
        /// </summary>
        public static string ViewManageNotificationsGeneration_MenuItemText {
            get {
                return ResourceManager.GetString(ResourceNames.ViewManageNotificationsGeneration_MenuItemText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'ManageDynamicResources_MenuItemText'.
            /// </summary>
            public const string ManageDynamicResources_MenuItemText = "ManageDynamicResources_MenuItemText";
            
            /// <summary>
            /// Stores the resource name 'ManageDynamicSettings_MenuItemText'.
            /// </summary>
            public const string ManageDynamicSettings_MenuItemText = "ManageDynamicSettings_MenuItemText";
            
            /// <summary>
            /// Stores the resource name 'ManageNotifications_MenuItemText'.
            /// </summary>
            public const string ManageNotifications_MenuItemText = "ManageNotifications_MenuItemText";
            
            /// <summary>
            /// Stores the resource name 'NotificationDefinitionEntityTypeDisplayName'.
            /// </summary>
            public const string NotificationDefinitionEntityTypeDisplayName = "NotificationDefinitionEntityTypeDisplayName";
            
            /// <summary>
            /// Stores the resource name 'SettingsExportFileName'.
            /// </summary>
            public const string SettingsExportFileName = "SettingsExportFileName";
            
            /// <summary>
            /// Stores the resource name 'ViewClientNotifications_MenuItemText'.
            /// </summary>
            public const string ViewClientNotifications_MenuItemText = "ViewClientNotifications_MenuItemText";
            
            /// <summary>
            /// Stores the resource name 'ViewGenericNotifications_MenuItemText'.
            /// </summary>
            public const string ViewGenericNotifications_MenuItemText = "ViewGenericNotifications_MenuItemText";
            
            /// <summary>
            /// Stores the resource name 'ViewManageNotificationsGeneration_MenuItemText'.
            /// </summary>
            public const string ViewManageNotificationsGeneration_MenuItemText = "ViewManageNotificationsGeneration_MenuItemText";
        }
    }
}
