// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Api.Irt.Shared;
using Frameworks.ExtendedProperties.Configuration;
using Frameworks.ExtendedProperties.Registries;
using Frameworks.ExtendedProperties.Services.Interfaces;
using IRT.Domain;
using IRT.Domain.ViewsSql.Study;
using IRT.Domain.ViewsSql.User;
using Kernel.AspNetMvc.Security.Services;
using Kernel.DDD.Dispatching;
using Unity;
using Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Contracts;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.OData.Query;
using Api.Irt.Common;

namespace Api.Irt.Modules.DataTransfer.Generic.ExtendedProperties.Controllers
{
    [Produces("application/json")]
    //
    //  Authorization Required : Guid.Parse("5032cd51-e96e-4149-b7ad-30cf4b4cf50e")
    //
    public partial class GenericEdcNotificationDefinitionSettingsExtendedPropertiesCrudController : ExtendedPropertiesApiController
    {
        public GenericEdcNotificationDefinitionSettingsExtendedPropertiesCrudController(
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext,
            ICommandBus commandBus,
            IContextService<StudySqlView, UserSqlView> contextService,
            IExtendedPropertiesFunctionConfigurator functionConfigurator,
            IExtendedPropertiesRegistry extendedPropertiesRegistry,
            IEntityDataService entityDataService) : base(
                httpContextAccessor,
                unityContainer,
                dbContext,
                commandBus,
                contextService,
                functionConfigurator,
                extendedPropertiesRegistry,
                entityDataService,
                Guid.Parse("5032cd51-e96e-4149-b7ad-30cf4b4cf50e"))
        {
    
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties")]
        [HttpGet]
        [EnableQuery(MaxExpansionDepth=15)]
        [Produces(typeof(IEnumerable<GenericEdcNotificationDefinitionSettingsNullTypeDto>))]
        public ActionResult ReadExtendedProperties()
        {
            return ReadExtendedPropertiesCrudWithDefault<GenericEdcNotificationDefinitionSettingsNullTypeDto, IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings>(OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", "NotificationDefinitionId", "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties/create")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult CreateExtendedProperties(
            GenericEdcNotificationDefinitionSettingsNullTypeDto value)
        {
            return CreateExtendedPropertiesCrud(OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", value.NotificationDefinitionId.ToString(), "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings", value, "NotificationDefinitionId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties/update")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult UpdateExtendedProperties(
            GenericEdcNotificationDefinitionSettingsNullTypeDto value)
        {
            return UpdateExtendedPropertiesCrud(OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", value.NotificationDefinitionId.ToString(), "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings", value, "NotificationDefinitionId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties/delete")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult DeleteExtendedProperties(
            GenericEdcNotificationDefinitionSettingsNullTypeDto value)
        {
            return DeleteExtendedPropertiesCrud(OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", value.NotificationDefinitionId.ToString(), "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings", value, "NotificationDefinitionId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties/export")]
        [HttpGet]
        [Produces("text/csv")]
        public ActionResult ExportExtendedProperties()
        {
            return ExportExtendedPropertiesCrud<GenericEdcNotificationDefinitionSettingsNullTypeDto>(OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings", "NotificationDefinitionId");
        }
        
        [SwaggerOperation(Tags = new [] { "IRT/v1 : ExtendedProperties : Entities" })]
        [Route("/api/irt/v1/extended-properties/generic-edc-notification-definition-settings/extended-properties/import")]
        [HttpPost]
        [ProducesResponseType(typeof(ActionResult), StatusCodes.Status200OK)]
        public ActionResult ImportExtendedProperties(IEnumerable<IFormFile> importFiles)
        {
            return ImportExtendedPropertiesCrud<GenericEdcNotificationDefinitionSettingsNullTypeDto>(importFiles, OperationId, "Frameworks.Notifications.Entities.NotificationDefinitionSqlView", "NotificationDefinitionId", "IRT.Modules.DataTransfer.Generic.Edc.Domain.ValueObjects.StudySettings.GenericEdcNotificationDefinitionSettings");
        }
        
    }
}