// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

namespace Api.Irt.Modules.DataTransfer.Generic.Events
{
	public class EventClassification : IrtApiCreator.ModuleSpecifics.Contracts.EventClassification.EventClassification, 
	IrtApiCreator.ModuleSpecifics.Contracts.EventClassification.IEventClassification
	{
		public EventClassification()
		{
			Declaration = new string[,]
			{

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.GenericDataGeneration.Events.GenericIntegrationDataEvent", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.DynamicSetting.Events.DynamicSettingCreated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.DynamicSetting.Events.DynamicSettingDllCreated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.ClientNotificationAdditionalInfoUpdated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.ClientNotificationCreated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.ClientNotificationReceived", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.ClientNotificationSent", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.ClientNotificationUpdated", "DTGeneric"},

                {"IRT.Modules.DataTransfer.Generic.Domain.Aggregates.ClientNotifications.Events.NotificationMarkedAsSent", "DTGeneric"}

			};
		}
	}
}