// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Globalization;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Queries.Controllers
{
    /// <summary>
    /// The generated side of
    /// ClientDataTransferErrorSummaryNotificationQueriesController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Queries")]
    // old routes -- [Route("api/IRT/v1/DTGeneric/Queries/ClientDataTransferErrorSummaryNotification")]
    [Produces("application/json")]
    public partial class ClientDataTransferErrorSummaryNotificationQueriesController : QueriesController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public ClientDataTransferErrorSummaryNotificationQueriesController
        (
            IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.DataServices.Errors.ClientDataTransferErrorSummaryNotificationDataService dataService,
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
            ClientDataTransferErrorSummaryNotificationDataService = dataService;
        }

        protected IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.DataServices.Errors.ClientDataTransferErrorSummaryNotificationDataService ClientDataTransferErrorSummaryNotificationDataService;    
    }
}
