// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Globalization;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Queries.Controllers
{
    /// <summary>
    /// The generated side of GenericScreenFailedNotificationQueriesController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Queries")]
    // old routes -- [Route("api/IRT/v1/DTGeneric/Queries/GenericScreenFailedNotification")]
    [Produces("application/json")]
    public partial class GenericScreenFailedNotificationQueriesController : QueriesController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public GenericScreenFailedNotificationQueriesController
        (
            IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.DataServices.GenericScreenFailedNotificationDataService dataService,
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
            GenericScreenFailedNotificationDataService = dataService;
        }
        
        /// <summary>
        /// CountryName handler endpoint
        /// </summary>
        /// <param name="countryCode">countryCode</param>
        [HttpGet]
        // old routes -- [Route("CountryName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/country-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetCountryName
        (
             string countryCode
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetCountryName
                (
                     countryCode
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// DepotCountryName handler endpoint
        /// </summary>
        /// <param name="depotId">depotId</param>
        [HttpGet]
        // old routes -- [Route("DepotCountryName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/depot-country-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetDepotCountryName
        (
             string depotId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetDepotCountryName
                (
                     depotId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// DepotName handler endpoint
        /// </summary>
        /// <param name="depotId">depotId</param>
        [HttpGet]
        // old routes -- [Route("DepotName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/depot-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetDepotName
        (
             string depotId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetDepotName
                (
                     depotId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// PILastName handler endpoint
        /// </summary>
        /// <param name="siteId">siteId</param>
        [HttpGet]
        // old routes -- [Route("PILastName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/p-i-last-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetPILastName
        (
             string siteId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetPILastName
                (
                     siteId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// SiteCountryName handler endpoint
        /// </summary>
        /// <param name="siteId">siteId</param>
        [HttpGet]
        // old routes -- [Route("SiteCountryName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/site-country-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetSiteCountryName
        (
             string siteId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetSiteCountryName
                (
                     siteId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
        /// <summary>
        /// SiteName handler endpoint
        /// </summary>
        /// <param name="siteId">siteId</param>
        [HttpGet]
        // old routes -- [Route("SiteName")]
         [Route("api/irt/v1/data-transfer-generic/queries/generic-screen-failed-notification/site-name")]
          [SwaggerOperation(Tags = new[] { "IRT : Queries : Data-transfer-generic" })]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        public ActionResult GetSiteName
        (
             string siteId
        )
        {
            ActionResult response;
            
            string result;
            
            try
            {
                result = GenericScreenFailedNotificationDataService.GetSiteName
                (
                     siteId
                );
                
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }

        protected IRT.Modules.DataTransfer.Generic.Edc.Domain.Notifications.DataServices.GenericScreenFailedNotificationDataService GenericScreenFailedNotificationDataService;    
    }
}
