//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Domain.SqlViews.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2025 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class GenericNotificationDefinition {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a GenericNotificationDefinition object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public GenericNotificationDefinition() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Domain.SqlViews.Resources.GenericNotifica" +
                                        "tionDefinition", typeof(GenericNotificationDefinition).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client'.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString(ResourceNames.Client, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Generic'.
        /// </summary>
        public static string Generic {
            get {
                return ResourceManager.GetString(ResourceNames.Generic, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rave'.
        /// </summary>
        public static string Rave {
            get {
                return ResourceManager.GetString(ResourceNames.Rave, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Self Transform'.
        /// </summary>
        public static string SelfTransform {
            get {
                return ResourceManager.GetString(ResourceNames.SelfTransform, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Veeva'.
        /// </summary>
        public static string Veeva {
            get {
                return ResourceManager.GetString(ResourceNames.Veeva, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Client'.
            /// </summary>
            public const string Client = "Client";
            
            /// <summary>
            /// Stores the resource name 'Generic'.
            /// </summary>
            public const string Generic = "Generic";
            
            /// <summary>
            /// Stores the resource name 'Rave'.
            /// </summary>
            public const string Rave = "Rave";
            
            /// <summary>
            /// Stores the resource name 'SelfTransform'.
            /// </summary>
            public const string SelfTransform = "SelfTransform";
            
            /// <summary>
            /// Stores the resource name 'Veeva'.
            /// </summary>
            public const string Veeva = "Veeva";
        }
    }
}
