// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Api.Irt.Common;
using IRT.Domain;

using Kernel.DDD.Dispatching;

using Swashbuckle.AspNetCore.Annotations;

using Unity;


namespace Api.Irt.Modules.DataTransfer.Generic.Commands.Controllers
{
    /// <summary>
    /// The generated side of DTGenericCommandsController
    /// </summary>
    // old routes -- [Realm("DTGeneric > Commands")]
    // old routes -- [Route("api/IRT/v1/DTGeneric/Commands")]
    [Produces("application/json")]
    public partial class DTGenericCommandsController : CommandsController
    {
        /// <summary>
        /// constructor
        /// </summary>
        public DTGenericCommandsController
        (
            ICommandBus commandBus,
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(commandBus, httpContextAccessor, unityContainer, dbContext)
        {
        }
        
        /// <summary>
        /// RaveAknowledgeClientNotification handler endpoint
        /// </summary>
        /// <param name="command">command</param>
        [HttpPost]
        // old routes -- [Route("RaveAknowledgeClientNotification")]
         [Route("api/irt/v1/data-transfer-generic/commands/rave-aknowledge-client-notification")]
         [SwaggerOperation(Tags = new[] { "IRT : Commands : Data-transfer-generic" })]
        [ProducesResponseType(typeof(Kernel.AspNetMvc.CommandResult), StatusCodes.Status200OK)]
        public ActionResult RaveAknowledgeClientNotification
        (
            IRT.Modules.DataTransfer.Generic.Edc.Domain.Aggregates.ClientNotifications.Commands.Rave.RaveAknowledgeClientNotification command
        )
        {
            ActionResult response;
            
            try
            {
                Kernel.AspNetMvc.RestApi.CommandResult result = SendCommand(command);
                
                if (result.IsSuccess)
                {
                    response = Ok(result);
                }
                else
                {
                    response = Fail(result);
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
            
            return response;
        }
        
    }
}
