// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.Extensions.Logging;
using Microsoft.OData.ModelBuilder;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Kernel.Globalization.Domain.Aggregates.LanguageAggregate.Enums;
using Kernel.OData.Contracts;

using Unity;
using Swashbuckle.AspNetCore.Annotations;


namespace Api.Irt.Modules.DataTransfer.Generic.EntityReads
{
    /// <summary>
    /// The standard controller for a DynamicDataTransferSetting entity.
    /// </summary>
    // old routes -- [Realm("DTGeneric > EntityReads")]
    // old routes -- [Route("IRT/v1/DTGeneric/IRT/DynamicDataTransferSetting")]
    [Produces("application/json")]
    public class DynamicDataTransferSettingEntityReadsController : EntityReadsController
    {
#region Constructors

        /// <summary>
        /// constructor
        /// </summary>
        public DynamicDataTransferSettingEntityReadsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

#endregion
        
        
        public static void RegisterModel(ODataModelBuilder builder)
        {
            builder.EntityType<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>().HasKey(e => new {e.EntityTypeName, e.ExtendedPropertiesTypeName, e.EntityId, e.ExtendedPropertyName, e.Value});
            builder.EntitySet<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>("DynamicDataTransferSettingSqlView");
        }
        
#region Reads
        
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
         [Route("irt/v1/data-transfer-generic/i-r-t/dynamic-data-transfer-settings")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>))]
        public ActionResult Get()
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>().AsQueryable();
        
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        }
        /// <param name="EntityTypeName">EntityTypeName</param>
        /// <param name="ExtendedPropertiesTypeName">ExtendedPropertiesTypeName</param>
        /// <param name="EntityId">EntityId</param>
        /// <param name="ExtendedPropertyName">ExtendedPropertyName</param>
        /// <param name="Value">Value</param>
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
        // old routes -- [Route("{EntityTypeName}/{ExtendedPropertiesTypeName}/{EntityId}/{ExtendedPropertyName}/{Value}")]
         [Route("irt/v1/data-transfer-generic/i-r-t/dynamic-data-transfer-settings/{EntityTypeName}/{ExtendedPropertiesTypeName}/{EntityId}/{ExtendedPropertyName}/{Value}")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView))]
        public ActionResult Get
        (
              string EntityTypeName
            , string ExtendedPropertiesTypeName
            , string EntityId
            , string ExtendedPropertyName
            , string Value
        )
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>().Where(entity => 
                     entity.EntityTypeName == EntityTypeName 
                     &&  entity.ExtendedPropertiesTypeName == ExtendedPropertiesTypeName 
                     &&  entity.EntityId == EntityId 
                     &&  entity.ExtendedPropertyName == ExtendedPropertyName 
                     &&  entity.Value == Value 
                );
        
                if (0 < result.Count())
                {
                    response = Ok(SingleResult.Create(result));
                }
                else
                {
                    response = NotFound();
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        } 
        
        /// <summary>
        /// Read an entity by the primary key, without embedded entities
        /// </summary>
        /// <param name="EntityTypeName">EntityTypeName</param>
        /// <param name="ExtendedPropertiesTypeName">ExtendedPropertiesTypeName</param>
        /// <param name="EntityId">EntityId</param>
        /// <param name="ExtendedPropertyName">ExtendedPropertyName</param>
        /// <param name="Value">Value</param>
        /// <returns>the entity if found, default otherwise</returns>
        protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView ReadByKeyWithoutEmbeds
        (
              string EntityTypeName
            , string ExtendedPropertiesTypeName
            , string EntityId
            , string ExtendedPropertyName
            , string Value
        )
        {
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView result = null;
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView read;
        
            try
            {
                read = ReadByKey
                (
                      EntityTypeName
                    , ExtendedPropertiesTypeName
                    , EntityId
                    , ExtendedPropertyName
                    , Value
                );
        
                if (read != null)
                {
                    result = new IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView()
                    {
                      EntityTypeName = read.EntityTypeName
                    , ExtendedPropertiesTypeName = read.ExtendedPropertiesTypeName
                    , EntityId = read.EntityId
                    , ExtendedPropertyName = read.ExtendedPropertyName
                    , Value = read.Value
                    };
                }
            }
            catch
            {
            }
        
            return result;
        }
        
#endregion
        
        
        /// <summary>
        /// Read an entity by the primary key
        /// </summary>
    /// <param name="EntityTypeName">EntityTypeName</param>
    /// <param name="ExtendedPropertiesTypeName">ExtendedPropertiesTypeName</param>
    /// <param name="EntityId">EntityId</param>
    /// <param name="ExtendedPropertyName">ExtendedPropertyName</param>
    /// <param name="Value">Value</param>
    /// <returns>the entity if found, default otherwise</returns>
    protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView ReadByKey
    (
          string EntityTypeName
        , string ExtendedPropertiesTypeName
        , string EntityId
        , string ExtendedPropertyName
        , string Value
    )
    {
        IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView result = null;

        try
        {
            result = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicDataTransferSettings.DynamicDataTransferSettingSqlView>().Where
            (s =>
                s.EntityTypeName.Equals(EntityTypeName)
                && s.ExtendedPropertiesTypeName.Equals(ExtendedPropertiesTypeName)
                && s.EntityId.Equals(EntityId)
                && s.ExtendedPropertyName.Equals(ExtendedPropertyName)
                && s.Value.Equals(Value)
            ).FirstOrDefault();
        }
        catch
        {
        }

        return result;
    }

    }

    /// <summary>
    /// input schema for the entity
    /// </summary>
    public class DynamicDataTransferSettingInput
    {
        /// <summary>
        /// EntityTypeName
        /// </summary>
        public string EntityTypeName {get; set;}
        
        /// <summary>
        /// ExtendedPropertiesTypeName
        /// </summary>
        public string ExtendedPropertiesTypeName {get; set;}
        
        /// <summary>
        /// EntityId
        /// </summary>
        public string EntityId {get; set;}
        
        /// <summary>
        /// ExtendedPropertyName
        /// </summary>
        public string ExtendedPropertyName {get; set;}
        
        /// <summary>
        /// Value
        /// </summary>
        public string Value {get; set;}
    }
}
