// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.Extensions.Logging;
using Microsoft.OData.ModelBuilder;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Kernel.Globalization.Domain.Aggregates.LanguageAggregate.Enums;
using Kernel.OData.Contracts;

using Unity;
using Swashbuckle.AspNetCore.Annotations;


namespace Api.Irt.Modules.DataTransfer.Generic.EntityReads
{
    /// <summary>
    /// The standard controller for a DynamicSetting entity.
    /// </summary>
    // old routes -- [Realm("DTGeneric > EntityReads")]
    // old routes -- [Route("IRT/v1/DTGeneric/IRT/DynamicSetting")]
    [Produces("application/json")]
    public class DynamicSettingEntityReadsController : EntityReadsController
    {
#region Constructors

        /// <summary>
        /// constructor
        /// </summary>
        public DynamicSettingEntityReadsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

#endregion
        
        
        public static void RegisterModel(ODataModelBuilder builder)
        {
            builder.EntitySet<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView>("DynamicSettingSqlView");
        }
        
#region Reads
        
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
         [Route("irt/v1/data-transfer-generic/i-r-t/dynamic-settings")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView>))]
        public ActionResult Get()
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView>().AsQueryable();
        
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        }
        /// <param name="DynamicSettingId">DynamicSettingId</param>
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
        // old routes -- [Route("{DynamicSettingId}")]
         [Route("irt/v1/data-transfer-generic/i-r-t/dynamic-settings/{DynamicSettingId}")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView))]
        public ActionResult Get
        (
              Guid DynamicSettingId
        )
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView>().Where(entity => 
                     entity.DynamicSettingId == DynamicSettingId 
                );
        
                if (0 < result.Count())
                {
                    response = Ok(SingleResult.Create(result));
                }
                else
                {
                    response = NotFound();
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        } 
        
        /// <summary>
        /// Read an entity by the primary key, without embedded entities
        /// </summary>
        /// <param name="DynamicSettingId">DynamicSettingId</param>
        /// <returns>the entity if found, default otherwise</returns>
        protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView ReadByKeyWithoutEmbeds
        (
              Guid DynamicSettingId
        )
        {
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView result = null;
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView read;
        
            try
            {
                read = ReadByKey
                (
                      DynamicSettingId
                );
        
                if (read != null)
                {
                    result = new IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView()
                    {
                      DynamicSettingId = read.DynamicSettingId
                    , Name = read.Name
                    , Description = read.Description
                    , DefaultValue = read.DefaultValue
                    , EntityTypeName = read.EntityTypeName
                    , ExtendedPropertyName = read.ExtendedPropertyName
                    };
                }
            }
            catch
            {
            }
        
            return result;
        }
        
#endregion
        
        
        /// <summary>
        /// Read an entity by the primary key
        /// </summary>
    /// <param name="DynamicSettingId">DynamicSettingId</param>
    /// <returns>the entity if found, default otherwise</returns>
    protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView ReadByKey
    (
          Guid DynamicSettingId
    )
    {
        IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView result = null;

        try
        {
            result = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.DynamicSetting.DynamicSettingSqlView>().Where
            (s =>
                s.DynamicSettingId.Equals(DynamicSettingId)
            ).FirstOrDefault();
        }
        catch
        {
        }

        return result;
    }

    }

    /// <summary>
    /// input schema for the entity
    /// </summary>
    public class DynamicSettingInput
    {
        /// <summary>
        /// DynamicSettingId
        /// </summary>
        public System.Guid DynamicSettingId {get; set;}
        
        /// <summary>
        /// Name
        /// </summary>
        public string Name {get; set;}
        
        /// <summary>
        /// Description
        /// </summary>
        public string Description {get; set;}
        
        /// <summary>
        /// DefaultValue
        /// </summary>
        public string DefaultValue {get; set;}
        
        /// <summary>
        /// EntityTypeName
        /// </summary>
        public string EntityTypeName {get; set;}
        
        /// <summary>
        /// ExtendedPropertyName
        /// </summary>
        public string ExtendedPropertyName {get; set;}
    }
}
