// -----------------------------------------------------------------------------
//   THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
// -----------------------------------------------------------------------------
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.Extensions.Logging;
using Microsoft.OData.ModelBuilder;

using Api.Irt.Common;
using Api.Irt.Shared;
using IRT.Domain;

using Kernel.Globalization.Domain.Aggregates.LanguageAggregate.Enums;
using Kernel.OData.Contracts;

using Unity;
using Swashbuckle.AspNetCore.Annotations;


namespace Api.Irt.Modules.DataTransfer.Generic.EntityReads
{
    /// <summary>
    /// The standard controller for a NotificationDependency entity.
    /// </summary>
    // old routes -- [Realm("DTGeneric > EntityReads")]
    // old routes -- [Route("IRT/v1/DTGeneric/IRT/NotificationDependency")]
    [Produces("application/json")]
    public class NotificationDependencyEntityReadsController : EntityReadsController
    {
#region Constructors

        /// <summary>
        /// constructor
        /// </summary>
        public NotificationDependencyEntityReadsController
        (
            IHttpContextAccessor httpContextAccessor,
            IUnityContainer unityContainer,
            IRTDbContext dbContext
        )
        : base(httpContextAccessor, unityContainer, dbContext)
        {
        }

#endregion
        
        
        public static void RegisterModel(ODataModelBuilder builder)
        {
            builder.EntitySet<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView>("NotificationDependencySqlView");
        }
        
#region Reads
        
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
         [Route("irt/v1/data-transfer-generic/i-r-t/notification-dependencies")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView>))]
        public ActionResult Get()
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView>().AsQueryable();
        
                response = Ok(result);
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        }
        /// <param name="NotificationId">NotificationId</param>
        //Use this to allow Kernel.OData module to determine what methods to register as odata masked endpoints
        //One can also use the "Get" as method name
        [HttpGet]
        //Use this attribute to enable standard odata support for a given method
        [EnableQuery(MaxExpansionDepth=15)]
        //Please use this attribute allow Kernel.OData module to determine how the endpoint should look like
        // old routes -- [Route("{NotificationId}")]
         [Route("irt/v1/data-transfer-generic/i-r-t/notification-dependencies/{NotificationId}")]
         [SwaggerOperation(Tags = new[] { "IRT : EntityReads : Data-transfer-generic" })]
        [Produces(typeof(IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView))]
        public ActionResult Get
        (
              Guid NotificationId
        )
        {
            ActionResult response;
        
            try
            {
                IQueryable<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView> result
                    = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView>().Where(entity => 
                     entity.NotificationId == NotificationId 
                );
        
                if (0 < result.Count())
                {
                    response = Ok(SingleResult.Create(result));
                }
                else
                {
                    response = NotFound();
                }
            }
            catch (Exception e)
            {
                response = Error(e);
            }
        
            return response;
        } 
        
        /// <summary>
        /// Read an entity by the primary key, without embedded entities
        /// </summary>
        /// <param name="NotificationId">NotificationId</param>
        /// <returns>the entity if found, default otherwise</returns>
        protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView ReadByKeyWithoutEmbeds
        (
              Guid NotificationId
        )
        {
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView result = null;
            IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView read;
        
            try
            {
                read = ReadByKey
                (
                      NotificationId
                );
        
                if (read != null)
                {
                    result = new IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView()
                    {
                      NotificationId = read.NotificationId
                    , DependsOnId = read.DependsOnId
                    , GroupKey = read.GroupKey
                    , CreatedAt = read.CreatedAt
                    };
                }
            }
            catch
            {
            }
        
            return result;
        }
        
#endregion
        
        
        /// <summary>
        /// Read an entity by the primary key
        /// </summary>
    /// <param name="NotificationId">NotificationId</param>
    /// <returns>the entity if found, default otherwise</returns>
    protected IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView ReadByKey
    (
          Guid NotificationId
    )
    {
        IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView result = null;

        try
        {
            result = DbContext.Set<IRT.Modules.DataTransfer.Generic.Domain.SqlViews.GenericNotificationDependency.NotificationDependencySqlView>().Where
            (s =>
                s.NotificationId.Equals(NotificationId)
            ).FirstOrDefault();
        }
        catch
        {
        }

        return result;
    }

    }

    /// <summary>
    /// input schema for the entity
    /// </summary>
    public class NotificationDependencyInput
    {
        /// <summary>
        /// NotificationId
        /// </summary>
        public System.Guid NotificationId {get; set;}
        
        /// <summary>
        /// DependsOnId
        /// </summary>
        public System.Guid? DependsOnId {get; set;}
        
        /// <summary>
        /// GroupKey
        /// </summary>
        public string GroupKey {get; set;}
        
        /// <summary>
        /// CreatedAt
        /// </summary>
        public System.DateTime CreatedAt {get; set;}
    }
}
