//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ClientNotifications.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2024 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Details {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Details object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Details() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ClientNot" +
                                        "ifications.Resources.Details", typeof(Details).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Attached file: {0}'.
        /// </summary>
        public static string AttachedFile {
            get {
                return ResourceManager.GetString(ResourceNames.AttachedFile, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client Notification Details'.
        /// </summary>
        public static string Breadcrumbs {
            get {
                return ResourceManager.GetString(ResourceNames.Breadcrumbs, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Close'.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString(ResourceNames.Close, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Date/Time: {0}'.
        /// </summary>
        public static string ContainerDateTime {
            get {
                return ResourceManager.GetString(ResourceNames.ContainerDateTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Title: {0}'.
        /// </summary>
        public static string ContainerTitle {
            get {
                return ResourceManager.GetString(ResourceNames.ContainerTitle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Body:'.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString(ResourceNames.Content, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dependent Notification:'.
        /// </summary>
        public static string DependentNotification {
            get {
                return ResourceManager.GetString(ResourceNames.DependentNotification, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client Notification Details'.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString(ResourceNames.Title, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Attached file: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AttachedFileFormat(object arg0) {
            return string.Format(_resourceCulture, AttachedFile, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Date/Time: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ContainerDateTimeFormat(object arg0) {
            return string.Format(_resourceCulture, ContainerDateTime, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Title: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ContainerTitleFormat(object arg0) {
            return string.Format(_resourceCulture, ContainerTitle, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'AttachedFile'.
            /// </summary>
            public const string AttachedFile = "AttachedFile";
            
            /// <summary>
            /// Stores the resource name 'Breadcrumbs'.
            /// </summary>
            public const string Breadcrumbs = "Breadcrumbs";
            
            /// <summary>
            /// Stores the resource name 'Close'.
            /// </summary>
            public const string Close = "Close";
            
            /// <summary>
            /// Stores the resource name 'ContainerDateTime'.
            /// </summary>
            public const string ContainerDateTime = "ContainerDateTime";
            
            /// <summary>
            /// Stores the resource name 'ContainerTitle'.
            /// </summary>
            public const string ContainerTitle = "ContainerTitle";
            
            /// <summary>
            /// Stores the resource name 'Content'.
            /// </summary>
            public const string Content = "Content";
            
            /// <summary>
            /// Stores the resource name 'DependentNotification'.
            /// </summary>
            public const string DependentNotification = "DependentNotification";
            
            /// <summary>
            /// Stores the resource name 'Title'.
            /// </summary>
            public const string Title = "Title";
        }
    }
}
