//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ClientNotifications.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2024 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Index {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Index object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Index() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("IRT.Modules.DataTransfer.Generic.Areas.StudyAdministration.Views.ClientNot" +
                                        "ifications.Resources.Index", typeof(Index).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client Notifications'.
        /// </summary>
        public static string Breadcrumbs {
            get {
                return ResourceManager.GetString(ResourceNames.Breadcrumbs, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Copy'.
        /// </summary>
        public static string CopyButtonLabel {
            get {
                return ResourceManager.GetString(ResourceNames.CopyButtonLabel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Create'.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString(ResourceNames.CreateButtonText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit'.
        /// </summary>
        public static string EditButtonLabel {
            get {
                return ResourceManager.GetString(ResourceNames.EditButtonLabel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Mark notifications as sent'.
        /// </summary>
        public static string MarkNotificationsButtonText {
            get {
                return ResourceManager.GetString(ResourceNames.MarkNotificationsButtonText, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Client Notifications'.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString(ResourceNames.Title, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View'.
        /// </summary>
        public static string ViewButtonLabel {
            get {
                return ResourceManager.GetString(ResourceNames.ViewButtonLabel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Breadcrumbs'.
            /// </summary>
            public const string Breadcrumbs = "Breadcrumbs";
            
            /// <summary>
            /// Stores the resource name 'CopyButtonLabel'.
            /// </summary>
            public const string CopyButtonLabel = "CopyButtonLabel";
            
            /// <summary>
            /// Stores the resource name 'CreateButtonText'.
            /// </summary>
            public const string CreateButtonText = "CreateButtonText";
            
            /// <summary>
            /// Stores the resource name 'EditButtonLabel'.
            /// </summary>
            public const string EditButtonLabel = "EditButtonLabel";
            
            /// <summary>
            /// Stores the resource name 'MarkNotificationsButtonText'.
            /// </summary>
            public const string MarkNotificationsButtonText = "MarkNotificationsButtonText";
            
            /// <summary>
            /// Stores the resource name 'Title'.
            /// </summary>
            public const string Title = "Title";
            
            /// <summary>
            /// Stores the resource name 'ViewButtonLabel'.
            /// </summary>
            public const string ViewButtonLabel = "ViewButtonLabel";
        }
    }
}
